<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bs.css'))
                ->prependStylesheet($this->basePath('css/treeview.css'))
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/nouislider.css'))
                ->prependStylesheet($this->basePath('css/saychas_z.css?' . time()))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                //->prependFile($this->basePath('/js/services.js'))
                ->prependFile($this->basePath('/js/cpanel.js'))
                ->prependFile($this->basePath('/js/nouislider.min.js'))
                ->prependFile($this->basePath('/js/nivo.slider.js'))
                ->prependFile($this->basePath('js/jquery.treeview.js'))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))
                ->prependFile($this->basePath('js/jquery.treeview.async.js'))
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.js'))
        ?>
        <style>
            #controlPanelContentId, #controlPanelContentId2, #controlPanelMenu {
                overflow: hidden;
            }
            #controlPanelMenu a {
                color: whitesmoke;
            }
            #controlPanelMenu a:active {
                color: yellow;
            }
            #controlPanelMenu a.active {
                color: white;
            }
/*            .container-dashboard {
                min-width: 80%;
            }*/
            .fluid-container .main-row {
                min-height: 100vh;
            }
            .fluid-container .card {
                min-height: 100%;
                height: 100%;
            }
            .min-height-50 {
                min-height: 50vh;
            }
            .min-height-100 {
                min-height: 100vh;
            }
            #controlPanelMenu a {
                color: whitesmoke;
            }
            #controlPanelMenu a:active {
                color: yellow;
            }
            #controlPanelMenu a.active {
                color: white;
            }
            


        </style>
    </head>
    <body>
        <div id="header" class="blokc" >
            <div id="headermenu" >
                <div class="headermenucontent">
                    <?= $this->partial('partials/menu-items', ['menuItems' => $this->menuItems]); ?>
                </div>
            </div>
        </div>
        <div class="fluid-container" style="overflow: hidden"> <?php //  container-dashboard ?>
            <div class="row main-row">
                <div class="col-sm-2 mt-0 pr-0">
                    <div class="card card-body bg-dark">
                        <ul id="controlPanelMenu" class="nav nav-pills flex-column">
                            <?= $this->partial('partials/sidebar-menu-items', ['menuItems' => $this->sidebarMenuItems]); ?>
                        </ul>
                    </div>
                </div>
                <div id="controlPanelContentId" class="col-sm-10 bg-light">
                    <?php // = $this->content ?>
                </div>
            </div>
        </div>
    </body>
</html>