<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/cpanel.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bs.css'))
                ->prependStylesheet($this->basePath('css/treeview.css'))
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/nouislider.css'))
                ->prependStylesheet($this->basePath('css/saychas_z.css?' . time()))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                //->prependFile($this->basePath('/js/services.js'))
                ->prependFile($this->basePath('/js/cpanel.js'))
                ->prependFile($this->basePath('/js/nouislider.min.js'))
                ->prependFile($this->basePath('/js/nivo.slider.js'))
                ->prependFile($this->basePath('js/jquery.treeview.js'))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))
                ->prependFile($this->basePath('js/jquery.treeview.async.js'))
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.js'))
        ?>
    </head>
    <body>
        <div class="fluid-container" style="overflow: hidden"> <?php //  container-dashboard ?>
            <div class="row">
                <div id="controlPanelContentId" class="col <?php // bg-light ?>">
                    <?php // = $this->content ?>
                    <div class="fluid-container login-form">banzaii</div>
                </div>
            </div>
        </div>
        <script>
            var loginForm = function() {
                $.ajax({
                    type: "POST",
                    url: "/control-panel/partner-login",
                    success: function (result, status, xhr) {
                        //console.log('result = ', result, 'status = ', status);
                        $('.login-form').html();
                        $('.login-form').html(result);
                    },
                    error: function (xhr, status, error) {
                        console.log('Login failed', xhr, status);
                    }
                });
            };
            loginForm(); 
        </script>
    </body>
</html>