<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('assets/control-panel/css/index.css'))
                ->prependStylesheet($this->basePath('css/cpanel.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bs.css'))
                ->prependStylesheet($this->basePath('css/treeview.css'))
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/nouislider.css'))
                ->prependStylesheet($this->basePath('css/saychas_z.css?' . time()))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                //->prependFile($this->basePath('/js/services.js'))
                ->prependFile($this->basePath('assets/js/control-panel/index.js'))
                ->prependFile($this->basePath('/js/calendar.js'))
                ->prependFile($this->basePath('/js/cpanel.js'))
                ->prependFile($this->basePath('/js/nouislider.min.js'))
                ->prependFile($this->basePath('/js/nivo.slider.js'))
                ->prependFile($this->basePath('js/jquery.treeview.js'))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))
                ->prependFile($this->basePath('js/jquery.treeview.async.js'))
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.js'))
        ?>
        <style>
            #controlPanelContentId, #controlPanelContentId2, #controlPanelMenu {
                overflow: hidden;
            }
            #controlPanelContentId {
              padding-right: 30px;
              margin-top: 15px;
            }
            .cp-stores-search {
              position relative;
            }
            .cp-stores-search button {
              position: absolute;
              right: 0;
              border-color: #ff5533;
              outline: none !important;
              transition: .5s;
              z-index: 5;
              box-shadow: none !important;
            }
            .cp-stores-search button:hover {
              color: #fff;
              background: #ff5533;
            }
            .cp-stores-search input {
              padding: .375rem .75rem .420rem !important;
              outline: none !important;
              box-shadow: none !important;
            }
            .cp-stores-search input:focus {
              border-color: #ff5533 !important;
            }
            .table-striped tbody tr:nth-of-type(odd) {
              background: rgba(0,0,0,.03);
            }
            .table tr:last-child td {
              border-bottom: 1px solid #dee2e6;
            }
            .active, .table-striped tbody tr.active:nth-child(odd) td {
              background: #ff5533;
            }
            .table-sm td, .table-sm th {
              padding: .3rem 1rem;
            }
            .table-sm th {
              font-weight: bold;
            }
            .main-body .card {
              height: 24em !important;
            }
            .page-link {
              color: #ff5533 !important;
            }
            #controlPanelMenu a {
                color: whitesmoke;
            }
            #controlPanelMenu a:active {
                color: yellow;
            }
            #controlPanelMenu a.active {
                color: white;
            }
            .fluid-container .main-row {
                min-height: 100vh;
            }
            .fluid-container .card {
                min-height: 100%;
                height: 100%;
            }
            .min-height-50 {
                min-height: 50vh;
            }
            .min-height-100 {
                min-height: 100vh;
            }
            #controlPanelMenu a {
                color: whitesmoke;
            }
            #controlPanelMenu a:active {
                color: yellow;
            }
            #controlPanelMenu a.active {
                color: white;
            }
        </style>
    </head>
    <body>
        <div class="fluid-container bg-dark" style="min-height: 40px; color: white; display: none;">
            <span style="position: absolute; right: 100px; top: 7px;"><?= null == $currentUser ? '' : $currentUser->getLogin() ?></span>
        </div>

        <div class="fluid-container"> <?php //  container-dashboard ?>
            <div class="row main-row">
                <div class="col-sm-2 mt-0 pr-0">
                    <div class="card card-body bg-dark" style="border-radius: 0">
                        <ul id="controlPanelMenu" class="nav nav-pills flex-column">
                            <?= $this->partial('partials/sidebar-menu-items', ['menuItems' => $this->sidebarMenuItems]); ?>
                        </ul>
                    </div>
                </div>
                <div id="controlPanelContentId" class="col-sm-10 bg-light">
                    <?php // = $this->content ?>
                </div>
            </div>
        </div>
    </body>
</html>
