<div class="product-card__files">
    <div class="product-card__file"><svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M28.999 0.999023C44.463 0.999023 56.999 13.535 56.999 28.999C56.999 44.463 44.463 56.999 28.999 56.999C13.535 56.999 0.998993 44.463 0.998993 28.999C0.998993 13.535 13.535 0.999023 28.999 0.999023Z" fill="white" stroke="#FF4B2D" stroke-width="2" />
        </svg>
        <a href="#">Инструкция для Samsung Galaxy Watch Active2 SM-R830 Ваниль <span>(2.5 Mb)</span></a>
    </div>
    <div class="product-card__file"><svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M28.999 0.999023C44.463 0.999023 56.999 13.535 56.999 28.999C56.999 44.463 44.463 56.999 28.999 56.999C13.535 56.999 0.998993 44.463 0.998993 28.999C0.998993 13.535 13.535 0.999023 28.999 0.999023Z" fill="white" stroke="#FF4B2D" stroke-width="2" />
        </svg>
        <a href="#">Скачать сертификат соответствия <span>(942.1 Kb)</span></a>
    </div>
    <br><br>
    <ul>
        <?php if(!empty($params)): ?>
            <?php while (list($key,$value)=each($params)):?>
                <li>
                    <?=$key?>: <?=$value?>
                </li>
            <?php endwhile;?>
        <?php endif;?>
    </ul>
</div>
