<section class="product-card__full-table" id="attributes">
    <?php if (!empty($characteristics[0])):?>
        <h2 class="product-card__section-heading">Характеристики</h2>
        <?php foreach ($characteristics[0] as $characteristic) : ?>
            <?php if ($characteristic['type'] == 0) :?>
                <h3><?= $characteristic['title'] ?></h3>
                <table>
            <?php else : ?>
                <tr>
                   <td><span><?= $characteristic['title'] ?></span></td>
                   <td><?= $characteristic['value'] ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($characteristic['type'] == 0) :?>
                </table>
            <?php endif; ?>
        <?php endforeach;  ?>
    <?php endif; ?>
</sections>