<section class="product-card__description">
    <?php if (!empty($description)) : ?>
        <h2 class="product-card__section-heading">Описание</h2>
        <div class="product-card__description-text <?=$description['if_spoiler'] ? '' : 'product-card__description-text--spoiler'?>">
           <?= $description['text'] ?>
        </div>
        <?php if (!$description['if_spoiler']): ?>
          <a class="product-card__description-toggle"></a>
        <?php endif; ?>
    <?php endif;?>
</section>
