<ul class="product-card__table product-card__table--justify">
    <?php if (!empty($characteristics[1])):?>
        <?php foreach($characteristics[1] as $characteristic):?>
            <li class="product-card__table-tr">
               <div class="product-card__table-th"><?=$characteristic['title']?></div>
               <div class="product-card__table-val"><?=$characteristic['value']?></div>
            </li>
        <?php endforeach;?>
    <?php endif;?>
</ul>
<a class="anchor product-card__to-table" href="#attributes">Все характеристики ↓</a>
