<div class="product-card__options">
    <div class="product-card__options-item">
        <h2 class="product-card__options-title">Цвет товара</h2>
        <ul class="product-card__options-products">
            <li class="product-card__options-img active"><img src="/images/products/product2.jpg" /></li>
            <li class="product-card__options-img"><img src="/images/products/product2.jpg" /></li>
            <li class="product-card__options-img"><img src="/images/products/product2.jpg" /></li>
         </ul>
    </div>
</div>