<div class="product-card__img-nav">
    <?php $imgClass = 'active';
    foreach ($images as $image) :?>
        <div class="product-card__small-img <?= $imgClass ?>">
            <img src="<?= $image_path.'/'.$image ?>" />
        </div>
    <?php $imgClass = '';   endforeach;?>
</div>
<div class="product-card__img">
    <div>
        <?php $imgClass = 'active';
            foreach ($images as $image) :?>
                <div class="product-card__big-img <?= $imgClass ?>">
                    <img src="<?= $image_path.'/'.$image ?>" />
                </div>
        <?php $imgClass = '';   endforeach;?>
    </div>
</div>
