<div id="testimonials" class="testimonials" data-id="<?=$id?>">
    <h2 class="product-card__section-heading">Отзывы о товаре </h2>
    <div v-if="images">
      <div v-if="images.length" class="testimonials__photos testimonials__photos--carousel">
          <div class="testimonials__photo" v-for="photo in images">
            <a :href="images_path + '/' + photo" data-fancybox="gallery">
              <img :src="images_path + '/' + photo" />
            </a>
          </div>
      </div>
      <div class="testimonials__sort">
        <div class="custom-select custom-select--radio">
          <div class="custom-select__label input">Сначала свежие</div>
          <div class="custom-select__dropdown">
            <div class="custom-select__dropdown-inner">
              <label class="custom-select__option">
                <input type="radio" checked="checked" value="0" name="sort" v-model="sortBy" @change="sortReviews" />
                <span>Сначала свежие</span>
              </label>
              <label class="custom-select__option">
                <input type="radio" value="1" name="sort" v-model="sortBy" @change="sortReviews" />
                <span>Сначала хорошие</span>
              </label>
              <label class="custom-select__option">
                <input type="radio" value="2" name="sort" v-model="sortBy" @change="sortReviews" />
                <span>Сначала отрицательные</span>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div class="testimonials__items">
          <div class="testimonials__item" v-for="review in reviews">
              <div class="testimonials__avatar">
                  <div class="testimonials__avatar-letter">{{ review.user_name[0] }}</div>
              </div>
              <div class="testimonials__content">
                  <div class="testimonials__heading">
                      <h3 class="testimonials__name">{{ review.user_name }}</h3>
                      <div class="testimonials__info">{{ review.time_created.toLocaleString() }}</div>
                  </div>
                  <div class="testimonials__grade">
                      <div :class="{'active': (+review.rating > 4) }">
                        <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="17px" height="17px">
                        <path fill-rule="evenodd"  fill="currentColor"
                        d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                        </svg>
                      </div>
                      <div :class="{'active': (+review.rating > 14) }">
                        <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="17px" height="17px">
                        <path fill-rule="evenodd"  fill="currentColor"
                        d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                        </svg>
                      </div>
                      <div :class="{'active': (+review.rating > 24) }">
                        <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="17px" height="17px">
                        <path fill-rule="evenodd"  fill="currentColor"
                        d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                        </svg>
                      </div>
                      <div :class="{'active': (+review.rating > 34) }">
                        <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="17px" height="17px">
                        <path fill-rule="evenodd"  fill="currentColor"
                        d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                        </svg>
                      </div>
                      <div :class="{'active': (+review.rating > 44) }">
                        <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        width="17px" height="17px">
                        <path fill-rule="evenodd"  fill="currentColor"
                        d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                        </svg>
                      </div>
                  </div>
                  <div class="testimonials__text">
                      {{ review.user_message }}
                  </div>
                  <div class="testimonials__answer" v-if="review.seller_message">
                      <div class="testimonials__answer-heading">
                          <h4 class="testimonials__store">{{ review.seller_name }}</h4>
                          <div class="testimonials__info">{{ review.timestamp.toLocaleString() }}</div>
                      </div>
                      <div class="testimonials__text">
                          {{ review.seller_message }}
                      </div>
                  </div>
              </div>
          </div>
          <button class="btn btn--secondary" v-if="(currentPage * limit.limit) < reviews_count)" @click="addReviews">Показать еще отзывы</button>
      </div>
    </div>
    <div v-else class="testimonials__empty">У этого товара еще нет ни одного отзыва. Будьте первым!</div>
</div>
<div>
    <div class="testimonials-panel">
        <div v-if="average_rating" class="testimonials-panel__info">
            <div class="testimonials-panel__grade">
                <div class="testimonials-panel__grade-val">{{ average_rating / 10 }}</div>
                <div class="testimonials-panel__grade-count"><span>{{ reviews_count }}</span> {{ reviewsUnit }}</div>
            </div>
            <div class="testimonials-panel__item"><span>5</span>
                <div class="testimonials-panel__graph">
                    <div class="testimonials-panel__graph-current" :style="{width: statisticsPercent('five') + '%'}"></div>
                </div><span>{{ statisticsPercent('five') }} %</span>
            </div>
            <div class="testimonials-panel__item"><span>4</span>
                <div class="testimonials-panel__graph">
                    <div class="testimonials-panel__graph-current" :style="{width: statisticsPercent('four') + '%'}"></div>
                </div><span>{{ statisticsPercent('four') }} %</span>
            </div>
            <div class="testimonials-panel__item"><span>3</span>
                <div class="testimonials-panel__graph">
                    <div class="testimonials-panel__graph-current" :style="{width: statisticsPercent('three') + '%'}"></div>
                </div><span>{{ statisticsPercent('three') }} %</span>
            </div>
            <div class="testimonials-panel__item"><span>2</span>
                <div class="testimonials-panel__graph">
                    <div class="testimonials-panel__graph-current" :style="{width: statisticsPercent('two') + '%'}"></div>
                </div><span>{{ statisticsPercent('two') }} %</span>
            </div>
            <div class="testimonials-panel__item"><span>1</span>
                <div class="testimonials-panel__graph">
                    <div class="testimonials-panel__graph-current"  :style="{width: statisticsPercent('one') + '%'}"></div>
                </div><span>{{ statisticsPercent('one') }} %</span>
            </div>
        </div>
        <div v-if="reviewer">
            <button class="btn btn--secondary" v-if="reviewer.result">Оставить отзыв</button>
            <div class="button-with-info" v-else>
              <button class="btn btn--secondary disabled">Оставить отзыв</button>
              <div class="button-with-info__info">
                <a :class="{'user-modal-open':(reviewer.errorCode == 403)}">{{ reviewer.errorDescription }}</a>
              </div>
            </div>
            <a class="testimonials-panel__link" href="#">Правила оформления отзывов →</a>
        </div>
    </div>
</div>
