<?php
//    $price = $card->receivePriceObject()->getPrice();
//    $oldPrice = $card->receivePriceObject()->getOldPrice();
    $rest = $card->receiveRest();
    $price = $card->getPrice();
    $oldPrice = $card->getOldPrice();
//    $images = $card->receiveProductImages();
    $image = $card->receiveFirstImageObject()->getHttpUrl();
//    $brand = $card->receiveBrandObject();
?>
<div class='productcard' >
    <div class="contentabsolute  content opacity".<?=$rest?> >
    <a  href="/product/<?= $card->getId()?>" >
        <div class="zeroblok">
            <img src="/img/zero.png" alt="alt" class="productimage zero"  style="background-image:url('<?=$this->imagePath('product');?>/<?= empty($image)?"nophoto_1.jpeg" : $image?>')"/>
        </div>
    </a>
    <strong class='blok producttitle'><a  href='/product/<?=$card->getId()?>' ><?=$card->getTitle() ?></a></strong>
    <div class='inactiveblok'></div>
    <span class='price'><?= number_format($price / 100, 0, ',', '&nbsp;') ?>&#8381;</span>
        <?=($oldPrice)?"<span class='oldprice'>".number_format($oldPrice / 100, 0, ',', '&nbsp;')." &#8381;</span>":"";?>
        <div class='payblockcard'>
        <div class='paybutton' rel='<?=$card->getId()?>' >в корзину</div>
    </div>
    </div>
    <div class="content opacity">
        <a  href="/product/<?= $card->getId() ?>" >
            <div class='zeroblok'>
                <img src='/img/zero.png' alt='alt' class="productimage zero" style="background-image:url('<?=$this->imagePath('product');?>/<?= empty($image)?"nophoto_1.jpeg" : $image?>')"/>
            </div>
        </a>
        <strong class='blok producttitle'><a  href="/product/<?= $card->getId()?>"><?= $card->getTitle() ?> </a></strong>
        <div class="inactiveblok"></div><span class="price"><?= number_format($price / 100, 0, ',', '&nbsp;') ?>&#8381;</span>
        <?=($oldPrice)?"<span class='oldprice'>".number_format($oldPrice / 100, 0, ',', '&nbsp;')."&#8381;</span>":"";?>
    </div>
</div>
