<style>
* {box-sizing: border-box;}
ul {list-style-type: none;}
/*body {font-family: Verdana, sans-serif;}*/

.month {
    padding: 35px 25px;
    width: 100%;
    background: #1abc9c;
    text-align: center;
}

.month ul {
    margin: 0;
    padding: 0;
}

.month ul li {
    color: #007bff; /*white;*/
    font-size: 20px;
    text-transform: uppercase;
    letter-spacing: 3px;
}

.month .prev {
    float: left;
    cursor: pointer;
    padding-top: 10px;
}

.month .next {
    float: right;
    cursor: pointer;
    padding-top: 10px;
}

.month .next:hover, .prev:hover {
    color: yellowgreen;
}

.weekdays {
    margin: 0;
    padding: 10px 0;
    background-color: #ddd;
}

.weekdays li {
    display: inline-block;
    width: 13.6%;
    color: #666;
    text-align: center;
}

.days {
    padding: 10px 0;
    background: #eee;
    margin: 0;
}

.days li {
    list-style-type: none;
    display: inline-block;
    width: 13.6%;
    text-align: center;
    margin-bottom: 5px;
    font-size:12px;
    color: #777;
    cursor: auto;
}

.days li span:hover {
    background-color: yellowgreen;
    padding: 5px;
    cursor: pointer;
}

.days li .active {
    padding: 5px;
    background: #007bff; /*#1abc9c;*/
    color: white !important
}

.bg-whitesmoke {
    background-color: whitesmoke;
}

.holiday {
/*    padding: 5px;
    background: red;*/
    color: red;
}

/* Add media queries for smaller screens */
@media screen and (max-width:720px) {
    .weekdays li, .days li {width: 13.1%;}
}

@media screen and (max-width: 420px) {
    .weekdays li, .days li {width: 12.5%;}
    .days li .active {padding: 2px;}
}

@media screen and (max-width: 290px) {
    .weekdays li, .days li {width: 12.2%;}
}
</style>

<div class="fluid-container align-self-sm-start">
    <div class="row">
        <div class="col-sm-6">
            <div class="month bg-whitesmoke">
              <ul>
                <li class="prev">❮</li>
                <li class="next">❯</li>
                <li>
                  Август<br>
                  <span style="font-size:18px">2017</span>
                </li>
              </ul>
            </div>

            <ul class="weekdays">
              <li>Пн</li>
              <li>Вт</li>
              <li>Ср</li>
              <li>Чт</li>
              <li>Пт</li>
              <li><span class="holiday">Сб</span></li>
              <li><span class="holiday">Вс</span></li>
            </ul>

            <ul class="days">  
                <li><span>01</span></li>
                <li><span>02</span></li>
                <li><span>03</span></li>
                <li><span>04</span></li>
                <li><span>05</span></li>
                <li><span>06</span></li>
                <li><span>07</span></li>
                <li><span>08</span></li>
                <li><span>09</span></li>
              <li><span class="active">10</span></li>
              <li><span class="holiday">11</span></li>
              <li><span>12<span></li>
              <li><span>13</span></li>
              <li><span>14</span></li>
              <li><span>15</span></li>
              <li><span>16</span></li>
              <li><span>17</span></li>
              <li><span>18</span></li>
              <li><span>19</span></li>
              <li><span>20</span></li>
              <li><span>21</span></li>
              <li><span>22</span></li>
              <li><span>23</span></li>
              <li><span>24</span></li>
              <li><span>25</span></li>
              <li><span>26</span></li>
              <li><span>27</span></li>
              <li><span>28</span></li>
              <li><span>29</span></li>
              <li><span>30</span></li>
              <li><span>31</span></li>
            </ul>
        </div>
        <div class="col-sm-6">
            banzaii
        </div>
    </div>
</div>