<div class="container p-0">
    <div class="main-body mt-1">

        <div class="card">
            <div class="card-header">
                <strong>Магазины</strong>
            </div>
            <div class="card-body">
                <table class="table table-striped table-sm">
                    <head>
                    <tr>
                        <th>Id</th>
                        <th>Название</th>
                        <th>Адрес</th>
                    </tr>
                    </head>
                    <div class="input-group mb-4 cp-stores-search">
                        <input type="search" class="form-control rounded" placeholder="Поиск магазина" aria-label="Search"
                               aria-describedby="search-addon" />
                        <button type="button" class="btn">Искать</button>
                    </div>
                    <?php foreach ($table as $row): ?>
                        <?= $this->partial('partials/stores/list-row', ['row' => $row]); ?>
                    <?php endforeach; ?>
                </table>
                <?= $this->partial('partials/stores/pagination'); ?>
            </div>
        </div>

    </div>

</div>
