<div class="container p-0">
    <div class="main-body mt-1">

        <div class="card">
            <div class="card-header">
                <strong>Магазины</strong>
            </div>
            <div class="card-body">
                <table class="table table-sm">
                    <head>
                    <tr>
                        <th><strong>Id</strong></th>
                        <th><strong>Название</strong></th>
                        <th><strong>Адрес</strong></th>
                    </tr>
                    </head>

                    <?php foreach ($table as $row): ?>
                        <?= $this->partial('control-panel/index/partials/stores/list-row', ['row' => $row]); ?>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>

    </div>

</div>
