<!--<nav aria-label="...">
  <ul class="pagination pagination-sm">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">1</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
  </ul>
</nav>-->
<nav aria-label="Page navigation example" style="position: absolute; bottom: 0em;">
  <ul class="pagination justify-content-left">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Пред</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#">След</a>
    </li>
  </ul>
</nav>