<div class="card mt-2">
    <div class="card-header">
        <strong>Расписание</strong>
    </div>
    <div class="card-body" style="min-height: 35vh; height: 35vh;">
        <?= $this->partial('partials/stores/time-table/calendar', ['year' => $dateTime->format('Y'), 'month' => $dateTime->format('m'), 'day' => $dateTime->format('d')]); ?>
        <button class="btn btn-secondary" style="position: absolute; bottom: 1em;">Сохранить</button>
    </div>
</div>
