<div class="card mt-1">
    <div class="card-header">
        <strong>Расписание</strong>
    </div>
    <div class="card-body" style="min-height: 50vh; height: 50vh;">
        <?= $this->partial('partials/stores/time-table/calendar', ['year' => $dateTime->format('Y'), 'month' => $dateTime->format('m'), 'day' => $dateTime->format('d')]); ?>
        <button class="btn btn-secondary" style="position: absolute; bottom: 1em;">Banzaii</button>
    </div>
</div>