<div class="modal-header">
    <h5 class="modal-title" id="usermodaltitle" ><?= $title ?></h5>
    <button type="button" class="close none2" data-dismiss="modal" aria-label="Close" id="usermodalclose">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    
    <div id='userAuthError'  class=" formcomment">Error block</div>

    <form method='POST' id='userAuthForm'>

        <div class="blok modaluserrow">
            <div class='pw-contentblock cblock-3 valign-top iblokr modalusertit' >
                <b >Телефон:</b>
            </div>
            <div class='pw-contentblock cblock-5 valign-top modaluserinf' >
                <input type='phone' name='userPhone' id='userPhone'  required class="phoneInput lableinfo short nobg"/>
            </div>
        </div>

        
        <?php if (true or $passBlock) { ?>
            <div class="blok modaluserrow">
                <div class='pw-contentblock cblock-3 valign-top iblokr modalusertit' >
                    <b >Пароль:</b>
                </div>
                <div class='pw-contentblock cblock-5 valign-middle modaluserinf' >
                    <input  name='userPass'  class="lableinfo short nobg"  id='userPass'/>
                    <span class="formcomment blok red pointer" id="forgetPass">Забыл пароль</span>
                </div>
            </div>     
        <?php } ?> 
        
        
        <?php if (true or $CodeBlock) { ?>
            <div class="blok modaluserrow">
                <div class='pw-contentblock cblock-3 valign-top iblokr modalusertit' >
                    <b >Код:</b>
                </div>
                <div class='pw-contentblock cblock-5 valign-middle modaluserinf' >
                    <input  name='userSmsCode'  class="smsInput lableinfo short nobg"  id='userSmsCode'/>
                    <span class="formcomment blok gray">Мы отправили его на телефон</span>
                    <span class="formcomment blok red pointer" id="oneMoreSms">Выслать еще раз</span>
                </div>
            </div>     
        <?php } ?>         
        
        <?php if (true or $UserBlock) { ?>
            <div class="blok modaluserrow">
                <div class='pw-contentblock cblock-3 valign-top iblokr modalusertit' >
                    <b >Имя, Фамилия</b>
                </div>
                <div class='pw-contentblock cblock-5 valign-middle modaluserinf' >
                    <input  name='userName'  class=" lableinfo  nobg"  id='userName'/>
                    
                </div>
            </div>     
        <div class="blok modaluserrow">
                <div class='pw-contentblock cblock-3 valign-top iblokr modalusertit' >
                    <b >Почта</b>
                </div>
                <div class='pw-contentblock cblock-5 valign-middle modaluserinf' >
                    <input  name='userMail'  class=" lableinfo  nobg"  id='userMail'/>
                    
                </div>
            </div>     
        <?php } ?>    

        <div class="blok">
            <div class='pw-contentblock cblock-3 valign-middle iblokl' >
              <?php if(!$stepOne) {?>  <span class="red pointer" >&larr; Вернуться</span> <?php } ?>
            </div>
            <div class='pw-contentblock cblock-5 valign-middle' >
                <input type="submit" value='<?= $buttonLable ?>' id='userAuthBotton' class=" userformsendbutton short">
            </div>
        </div>


        <!--div class='blok none  newuser'  id='sms' >
            <span class='blok mini'>Представьтесь</span>
            <input type='phone' name='userNameInput' class="nameInput" id='nameInput' />
        </div>
        
        <div class='blok none  olduser PT'  id='oldUser' >...</div>
    
        <div class='blok none  newuser'  id='sms' >
            <span class='blok mini'>Код из СМС (7777)</span>
            <input  name='userSmsCode'  class="smsInput"  id=''/>
        </div>
        
        <div class='blok none  olduser'  id='pass' >
            <span class='blok mini'>Пароль</span>
            <input type='phone' name='userPass'  class="smsInput"  id=''/>
        </div>
        
        <div class='blok' ><input type="submit" value='Войти' id='userAuthBotton' class="formsendbutton short"></div -->
        
    </form>




</div>