<div class="popup__heading" id="usermodaltitle"><?= $title ?? "" ?></div>
<div class="auth-reg">
  <div class="auth-reg__input-group">
      <div class="auth-reg__input-group__label">Телефон:</div>
      <?php if (empty($user['phone']) or !empty($error["phone"])) : ?>
        <div class="auth-reg__input-group__input">
          <input name='userPhone' id='userPhone' class="phoneinput <?= !empty($error['phone']) ? 'error' : '' ?>" type="text" placeholder="+7 (999) 999-99-99" required />
        </div>
        <?php if (!empty($error["phone"])):?>
          <p class="error"><?= $error["phone"] ?></p>
        <?php endif; ?>
      <?php else:?>
        <div class="auth-reg__input-group__value"><?= $user['phone'] ?? "" ?></div>
        
      <?php endif;  ?>
  </div>
  <?php /*if (false and $passBlock) : ?>
    <div class="auth-reg__input-group">
        <div class="auth-reg__input-group__label">Код:</div>
        <div class="auth-reg__input-group__input">
          <input name='userPass' type="text" class="<?= ($error['password']) ? 'error' : '' ?>" id='userPass' required />
          <?php if ($error["password"]):?>
            <p class="error"><?= $error["password"] ?></p>
          <?php endif; ?>
        <p>Сейчас мы вам позвоним, в течении минуты. Последние четыре цифры телефона входящего звонка - это и есть код.</p>     
          <!-- input type="hidden" id="forgetPassHidden" name="forgetPassHidden"  value="<?=($user['passforget'])?"1":"0"?>" -->
          <!-- a id="forgetPass">Забыли пароль?</a -->
        </div>
    </div>
  <?php endif; */ ?>
  <?php if (!empty($CodeBlock)) :
     /* if (false and $user['smscode']) :?>
        <input type="hidden"  name='userSmsCode'  value="<?=$user['smscode']?>" />
      <?php  else:  */?>
        <div class="auth-reg__input-group">
            <div class="auth-reg__input-group__label">Код:</div>
            <div class="auth-reg__input-group__input">
                <input name='userSmsCode' type="password" class="<?= !empty($error['sms']) || !empty($error['smscode']) ? 'error' : '' ?>" id='userSmsCode' required />
                <?php if (!empty($error["sms"])):?>
                  <p class="error"><?= $error["sms"] ?></p>
                <?php else:
                  if (!empty($error['smscode'])):?>
                    <p class="error"><?= $error["smscode"] ?></p>
                  <?php endif; ?>
                  <p>Сейчас мы вам позвоним, в течении минуты. Последние четыре цифры телефона входящего звонка - это и есть код.</p>
                <?php endif; ?>

                  <a  herf="#" id="oneMoreSms" >Позвонить еще раз?</a>
                  <input type="hidden"  name="recall"  value="0"   id="recall" >
            </div>
        </div>
      <?php //endif; ?>
  <?php endif; ?>
  <?php /*if ($passForgetBlock): ?>
    <div class="auth-reg__input-group">
        <div class="auth-reg__input-group__label">Новый пароль:</div>
        <div class="auth-reg__input-group__input">
          <input name='forgetPassInput' type="password" value="<?=$user["newpassword"]?>" class="<?= ($error['newpassword']) ? 'error' : '' ?>" id='userPass' required />
          <?php if ($error["newpassword"]):?>
            <p class="error"><?= $error["newpassword"] ?></p>
          <?php endif; ?>
          <p>Минимум 6 символов</p>
          <p>Сочетание букв и цифр</p>
        </div>
    </div>
    <div class="auth-reg__input-group">
        <div class="auth-reg__input-group__label">Еще раз:</div>
        <div class="auth-reg__input-group__input">
          <input name='forgetPassInput2' value="<?=$user["newpassword2"]?>" type="password" class="<?= ($error['newpassword2']) ? 'error' : '' ?>" id='userPass' required />
          <?php if ($error["newpassword2"]):?>
            <p class="error"><?= $error["newpassword2"] ?></p>
          <?php endif; ?>
          <input type="hidden" id="forgetPassHidden" name="forgetPassHidden"  value="1" >
        </div>
    </div>
  <?php endif; */?>
  <?php if (!empty($UserBlock)) : ?>
    <div class="auth-reg__input-group">
        <input type="hidden" name ="userblok_post" value="1" >
        <div class="auth-reg__input-group__label">Ваше имя:</div>
        <div class="auth-reg__input-group__input auth-reg__input-group__input--large">
          <input name='userName' type="text" class="<?= !empty($error['username']) ? 'error' : '' ?>" id='userName' value="<?= $user["username"] ?? "" ?>" required />
          <?php if (!empty($error["username"])):?>
            <p class="error"><?= $error["username"] ?></p>
          <?php endif; ?>
        </div>
    </div>
    <div class="auth-reg__input-group">
        <div class="auth-reg__input-group__label">Почта:</div>
        <div class="auth-reg__input-group__input auth-reg__input-group__input--large">
          <input name='userMail' type="email" class="<?= !empty($error['usermail']) ? 'error' : '' ?>" id='userMail'  value="<?= $user["usermail"] ?? "" ?>" required />
          <?php if (!empty($error["usermail"])):?>
            <p class="error"><?= $error["usermail"] ?></p>
          <?php endif; ?>
        </div>
    </div>
  <?php endif; ?>
  <?php if (!empty($user['passforget'])) : ?>
    <a class="auth-reg__back" id="goStepPass">← Вернуться</a>
  <?php elseif (!empty($stepOne)): ?>
    <a class="auth-reg__back" id="goStepOne">← Вернуться</a>
  <?php endif; ?>
  <input type="submit" value='<?= $buttonLable ?? "" ?>' id='userAuthButton' class="userformsendbutton btn btn--primary">
  <p class="error1c"><?= $error["1c"] ?? "" ?></p>
</div>
