
<div class="cart-payment">
    <h2 class="h2">Оплата  </h2>
    <div class="cart__radio-group">
        <?php if(!empty($cardinfo)) :?>
          <input type="radio" name='paycard' <?=($paycard)?"checked":""?> id="payment1" value="1" />
          <div class="cart__radio">
            <label for="payment1"><span class="cart__radio-check"></span><span><b>Оплата с привязанной карты</b></span></label>
              <div class="cart__radio-content">
              
                <select name="cardinfo" class="select">
                    <?php foreach ($cardinfo as $card):?>
                      <option value="<?=strip_tags($card["id"])?>" <?=($default == $card["id"])?"selected":""?> ><?=$card["pan"]?></option>
                   <?php endforeach;?>   
                </select>
              </div>
          </div>
        <?php endif;?>
        <input type="radio" name='paycard' <?=(!$paycard or !$cardinfo)?"checked":""?> id="payment2" value="0" />
        <div class="cart__radio">
            <label for="payment2"><span class="cart__radio-check"></span><span><b>Оплата новой картой</b></span></label>
            <div class="cart__radio-content">
                <p>Расплачивайтесь — мы запомним данные вашей карты, что бы не вводить её в следущий раз</p>
            </div>
        </div>
    </div>
</div>
