<?php    if ($countStors < 2 ) {  $ordermerge = false;  }?>   
<?php    if( $countStors) {?>
    <div class='contentpadding'>
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio <?=(!$ordermerge)?"zach":""?>  black radiomergebut' rel='dostmerge' for='dostmergeoff'> 
                    <b> 
                         <span class='iblok valign-middle '>Доставки из <?=$countStors?> магазинов </span> 
                         <span class='iblok valign-middle saychas'>за 1 час</span> 
                         <span class='iblok valign-middle '> &mdash;&nbsp;<?=number_format($hourPrice/100,0,"","&nbsp;")?>&nbsp;₽  </span> 
					</b>
		</div>
                <span class='blok gray text'>
                    Для каждого магазина мы назначим отдельного курьера, 
                    тем самым за час вы получите все свои товары в <?=($countStors == 1)?"$countStors доставке":"$countStors доставках"?>
                    <hr>
                    <span class="mini">крайнее время заказа: <?=date("r", $timeClose - 3600)?></span>
                </span>
<?php if($select1hour and !empty($select1hour)){?>                
                <select  class='lableinfo text timepoint' name="timepoint[0]" id="timepoint--dostmergeon" >
                       <option value="0">сейчас за час</option>
                <?php foreach($select1hour as $option){?>
                    <option value="<?=$option['value']?>"><?=$option['lable']?></option>
               <?php } ?>                 
        </select>
<!--pre><?=print_r($select1hour)?></pre -->
                
<?php } else { echo "<h4>Нет доставки</h4>"; }?>                
             </div>
        </div>
        
 <?php    if($countStors > 1) {?>       
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio radio <?=($ordermerge)?"zach":""?> black radiomergebut' rel='dostmerge' for='dostmergeon'> 
                     <b>
                         <span class='iblok valign-middle '>Объеденить заказы </span> 
                         <span class='iblok valign-middle saychas'>за 3 часа</span> 
                         <span class='iblok valign-middle '> &mdash;&nbsp;<?=number_format($hour3Price/100,0,"","&nbsp;")?>&nbsp;₽  </span> 
                     </b>
		</div>
                <span class='blok gray text' >
                    На каждые четыре магазина мы назначим по курьеру, 
                    тем самым, вы получите все свои товары 
                    в одной доставке (правда, это будет дольше)
                     <hr>
                    <span class="mini">крайнее время заказа: <?=date("r", $timeClose - 3600*3)?></span>
                </span>
          <?php if($select3hour and !empty($select3hour)){?>                
                <select  class='lableinfo text timepoint' name="timepoint[0]" id="timepoint-dostmergeon" >
                       
                <?php foreach($select3hour as $option3){?>
                    <option value="<?=$option3['value']?>"><?=$option3['lable']?></option>
               <?php } ?>                 
        </select>
                <!--pre><?=print_r($select3hour)?></pre -->

                
<?php } else { echo "<h4>Нет доставки</h4>"; }?>    
                
            </div>
        <?php } ?>    
            <input type="radio" name='ordermerge' class='relradiodostmerge none fltrcheckdostmergeon' value='1'  radio <?=($ordermerge)?"checked":""?>>
            <input type="radio" name='ordermerge' class='relradiodostmerge none fltrcheckdostmergeoff' value='0' checked <?=(!$ordermerge)?"checked":""?> >
        </div>
    </div>
<?php } ?>  