<?php use Application\Resource\Resource; ?>
<div class="panel__delivery">
    <?php if($countDelevery and $addressDelevery and $payEnable):?>
      <div class="panel__delivery-item">
          <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
          </svg>
          <div>
              <h2><?=Resource::ORDER_DELIVERY_TITLE?></h2>
              <p><?=$countDeleveryText?>, <?=$timeDelevery?> <?=$addressDelevery?></p>
          </div>
      </div>
    <?php endif;?>
    <?php if($countSelfdelevery):?>
      <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
          </svg>
          <div>
              <h2><?=Resource::ORDER_PICKUP_TITLE?></h2>
              <p><?=$countSelfdelevery?> <?=($countSelfdelevery == 1)?"магазина":"магазинов" ?></p>
          </div>
      </div>
    <?php endif;?>
    <?php if($payEnable ):?>
      <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
          </svg>
          <div>
              <h2><?=Resource::ORDER_PAYMENT_TITLE?></h2>
              <p><?=($paycard and $cardinfo)?Resource::ORDER_MEMBER_PAYCARD_TITLE."<span class='panel__cardnumber'>$cardinfo</span>":Resource::ORDER_NEW_PAYCARD_TITLE?></p>
          </div>
      </div>
    <?php endif;?>
</div>
<div class="panel__zip"></div>
<div class="panel__price">
    <div class="panel__price-current"><span id="basketpricetotalall"><?=number_format(((int)($basketpricetotalall + $priceDelevery )/100), 0, ',', '&nbsp;')?></span> ₽</div>
    <?php if($basketoldpricetotalall):?>
      <div class="panel__price-old"><span id="basketoldpricetotal"><?=$basketoldpricetotalall ?></span> ₽</div>
    <?php endif; ?>
</div>
<!-- div class="panel__bonuses"><span>+179</span> сейбонов<div class="question">
        <div class="question__icon">?</div>
    </div>
</div -->
<div class="panel__table">
    <div class="panel__tr">
        <div>Товары (<span id="basketproductcount"><?=$productcount?></span>)</div>
        <div class="panel__tr-items-total">
            <div><?=number_format(((int)$producttotal/100), 0, ',', '&nbsp;')?> ₽</div>
            <?php if ($basketoldpricetotal):?>
              <div><?=$basketoldpricetotal?> ₽</div>
            <?php endif; ?>
        </div>
    </div>
    <?php if ($countDelevery) :?>
      <div class="panel__tr">
          <div> <b><?= Resource::ORDER_DELIVERY_TITLE?><?=(!$ordermerge) ? Resource::BASKET_SAYCHAS_short : Resource::BASKET_SAYCHAS3_short?> (<?=$countDelevery?>)</b></div>
          <div><?=number_format(($priceDelevery/100),0,",","&nbsp;")?> ₽</div>
      </div>
    <?php endif; ?>

    <?php if ($countSelfdelevery) :?>
      <div class="panel__tr">
          <div><?= Resource::ORDER_PICKUP_TITLE?>(<?=$countSelfdelevery?>)</div>
          <div><?=($countSelfdelevery * $priceSelfdelevery) ?> ₽</div>
      </div>
    <?php endif; ?>
    <input type="hidden" name ="delivery_price" value="<?=$priceDelevery?>" />
</div>
<?php if(!$payEnable):?>
  <div class="overcoverlocal"></div>
<?php endif;?>
  <div class="btn btn--primary" id="sendbasketbutton"><?= Resource::ORDER_PAYMENT_BUTTON ?></div>
  <div class="panel__notice"><?= Resource::ORDER_AGGREMENT_NOTES ?></div>
