<div class="contentpadding"><?php
     print_r($this->post)
;?>
</div>

<?php if($countDelevery and $addressDelevery):?>  
<div class='contentpadding nopad'>
<div class='delevery-item delevery-door' > 
                <b class='blok'>Доставка </b>
                <div class='blok'><?=$timeDelevery?></div>
                <div class='blok'><?=$addressDelevery?></div>
            </div>
</div>
  <?php endif;?>
  <?php if($storeAdress){?>            
    <div class='contentpadding nopad'>
        <div class='delevery-item delevery-self' > 
                <b class='blok'>Самовывоз</b>
                <div class='blok'><?=$storeTime?></div>
                <ol>
    <?php foreach ($storeAdress as $adress) {?>
        <li ><?=$adress?></li>
    <?php }?>
        </ol>
            </div>
       </div> 
  <?php } ?>
<?php if(true ):?>
    <div class='contentpadding nopad'>
            <div class='delevery-item delevery-self' > 
                <b class='blok'>Оплата</b>
               
                <div class='blok'>
                    
<?=($paycard and $cardinfo)?"Оплата с привязанной карты <span class='blok gray'>$cardinfo</span>":"Оплатить банковской картой"?></div>
            </div>
    </div>
<?php endif;?>

        <div class='volna' ></div>  
        <div class='contentpadding '>
            <h2 class='blok price' ><tag id="basketpricetotalall"><?=number_format(((int)($basketpricetotalall + $priceDelevery )/100), 0, ',', '&nbsp;')?></tag>&#8381; 
    <?php if($basketoldpricetotalall){?> <span class='oldprice' ><span id="basketoldpricetotal"><?=$basketoldpricetotalall ?></span>&nbsp;&#8381;</span><?php }?>
            </h2>
            <div class='char-row'>
                <span class='char-title'>
                    <span>Товары(<tag id="basketproductcount"><?=$productcount?></tag>)</span>
                </span><span class=char-value >
                    <span><?=number_format(((int)$producttotal/100), 0, ',', '&nbsp;')?>&#8381; 
    <?php if($basketoldpricetotal) {?><tag class='oldprice'><?=$basketoldpricetotal?>&#8381;</tag> <?php }?></span>
                </span>
            </div>
    <?php if ($countDelevery) {?>            
            <div class='char-row'>
                <span class='char-title'>
                    <span><strong>Доставка <?=(!$ordermerge)?" за час":"за три часа"?>(<?=$countDelevery?>)</strong></span>
                </span><span class=char-value >
                    <span><strong><?=number_format(($priceDelevery/100),0,",","&nbsp;")?>&#8381;</strong></span>
                </span>
            </div>
    <?php }?>        
    <?php if ($countSelfdelevery) {?>        <div class='char-row'>
                <span class='char-title'>
                    <span>Самовывоз(<?=$countSelfdelevery?>)</span>
                </span><span class=char-value >
                    <span><?=($countSelfdelevery * $priceSelfdelevery) ?>&#8381;</span>
                </span>
            </div>
   <?php }?>
            <div class='contentpadding'>
                <div class=paybutton  >перейти к оплате</div>
            </div>

            <div class='contentpadding'>
                <div class='gray mini'  >Нажимая на кнопку, вы соглашаетесь с <a href=# class="red" >Условиями обработки перс. данных</a>, а также с <a href=# class="red" >Условиями продажи</a></div>
            </div>

        </div>    