<?php
if ($countStors < 2) {
  $ordermerge = false;
}
?>

<?php if ($countStors) :?>

  <div class="cart__radio-group">
      <input name='ordermerge' value="0" type="radio" <?= (!$ordermerge) ? 'checked' : '' ?> id="delivery1" />
      <div class="cart__radio">
        <label for="delivery1">
          <span class="cart__radio-check"></span>
          <span><b>Из <?= $countStors ?> магазинов <span class="accent">за 1 час</span>
          </b> &mdash;&nbsp;<?= number_format($hourPrice / 100, 0, "", "&nbsp;") ?>&nbsp;₽</span>
        </label>
        <div class="cart__radio-content">
              <p>Для каждого магазина мы назначим отдельного курьера, тем самым за час вы получите все свои товары в <?=$countStors?><?= ($countStors == 1) ? " доставке" : " доставках" ?>. <br>Крайнее время доставки - <?= date("r", $timeClose - 3600) ?>.</p>
              <?php if ($select1hour && !empty($select1hour)) : ?>
                <select class="select" name="timepoint[0]" id="timepoint-dostmerge1" rel="timepointtext1">
                  <?php foreach ($select1hour as $option) : ?>
                      <option value="<?= $option['value'] ?>" rel="<?= $option['rel'] ?> "  <?= $selectedtimepoint[0][$option['value']] ?> ><?= $option['lable'] ?></option>
                  <?php endforeach; ?>
                </select>
              <?php else: ?>
                <div class="timepoint">Нет доставки</div>
              <?php endif;?>
        </div>
      </div>
      <?php if ($countStors > 1) :?>
        <input name='ordermerge' value="1" type="radio" <?= ($ordermerge) ? 'checked' : '' ?> id="delivery2" />
        <div class="cart__radio">
          <label for="delivery2">
            <span class="cart__radio-check"></span>
            <span><b>Объединить заказы за 3 часа</b> &mdash;&nbsp;<?= number_format($hour3Price / 100, 0, "", "&nbsp;") ?>&nbsp;₽</span>
          </label>
            <div class="cart__radio-content">
                <p>На каждые 4 магазина мы назначим по курьеру, тем самым вы получите все свои товары в 2 доставках (правда это будет дольше).<br>Крайнее время доставки - <?= date("r", $timeClose - 3600 * 3) ?>.</p>
                <?php if ($select3hour && !empty($select3hour)): ?>
                  <select class="select" name="timepoint[1]" id="timepoint-dostmerge3" rel="timepointtext3">
                    <?php foreach ($select3hour as $option3): ?>
                      <option value="<?= $option3['value'] ?>" rel="<?= $option3['rel'] ?>" <?= $selectedtimepoint[1][$option3['value']] ?>><?= $option3['lable'] ?></option>
                    <?php endforeach; ?>
                  </select>
                <?php else: ?>
                  <div class="timepoint">Нет доставки</div>
                <?php endif;?>
            </div>
        </div>
      <?php endif;?>
  </div>
  <input type="hidden" name="timepointtext1" id="timepointtext1"  value="<?= $timepointtext1 ?>">
  <input type="hidden" name="timepointtext3" id="timepointtext3"  value="<?= $timepointtext3 ?>">

<?php endif; ?>
