<div class="catalog__sort">
  <div class="custom-select custom-select--radio">
    <div class="custom-select__label input">Сначала свежие</div>
    <div class="custom-select__dropdown">
      <div class="custom-select__dropdown-inner">
        <label class="custom-select__option">
          <input type="radio" checked="checked" value="0" name="sort" v-model="sort" @change="sortProducts" />
          <span>Сначала свежие</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="1" name="sort" v-model="sort" @change="sortProducts" />
          <span>Сначала популярные</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="2" name="sort" v-model="sort" @change="sortProducts" />
          <span>Сначала дешевые</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="3" name="sort" v-model="sort" @change="sortProducts" />
          <span>Сначала дорогие</span>
        </label>
      </div>
    </div>
  </div>
</div>
