<div class="catalog__sort">
  <div class="custom-select custom-select--radio" style="display:none;">
    <div class="custom-select__label input">Сначала свежие</div>
    <div class="custom-select__dropdown">
      <div class="custom-select__dropdown-inner">
        <label class="custom-select__option">
          <input type="radio" checked="checked" value="" name="sort" />
          <span>Сначала свежие</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="" name="sort" />
          <span>Сначала популярные</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="" name="sort" />
          <span>Сначала дешевые</span>
        </label>
        <label class="custom-select__option">
          <input type="radio" value="" name="sort" />
          <span>Сначала дорогие</span>
        </label>
      </div>
    </div>
  </div>
</div>
