<div class="iblok contentwrapper">
                <div id="topmenu" >
                    <ul>
                        <li><a href="/catalog/000000002" >Электроника</a></li> 
                        <li><a href=# >Аксессуары</a></li> 
                        <li><a href=# >Одежда</a></li> 
                        <li><a href=# >Детям</a></li> 
                        <li><a href=# >Продукты</a></li> 						
                        <li><a href=# >Афиша</a></li> 						
                        <li><a href=# >Билеты</a></li> 						
                        <li><a href=# >Услуги</a></li> 						
                    </ul>
                </div>
</div>