<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"  data-show="true" data-keyboard="false" data-backdrop="static" id="ServiceModalWindow" >
    <div class="modal-dialog modal-dialog-middle modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" ></h5>
                <button type="button" class="close none2" data-dismiss="modal" aria-label="Close" id="servicemodalclose">
                    <span aria-hidden="true">&times;</span>

                </button>
            </div>
            <div class="modal-body">
                <div  id='ServiceModalWraper' style="min-height:80px;">
. . . . .
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</div>