<div class="popup" id="usermodalwindow">
  <div class="popup__inner">
      <div class="popup__close"></div>
      <div class="popup__content">
        <form method='POST' id='userAuthModalForm' class="blok relative">

            <?=
            $this->partial("/application/common/auth-form-in-modal", [
                "title" => "Вход или регистрация",
                "buttonLable" => "Продолжить",
            ])
            ?>
        </form>
      </div>
  </div>
</div>
