<script>$(function () {
        $('#usermodalwindow').modal('show')
    })</script>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"  data-show="true" data-keyboard="false" data-backdrop="static" id="usermodalwindow">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method='POST' id='userAuthModalForm'>
                <?=
                $this->partial("/application/common/auth-form-in-modal", [
                    "title" => "Вход или регистрация",
                    "buttonLable" => "Продолжить",
                ])
                ?>  
            </form>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>