<li>имя: <?=$user->getName()?></li>
<li>телефон: <?=$userPhone?></li>
<?php
   ///$content.="<li>пароль: {$user->getPassword()}</li>";
        if(count($userData)){//$uesrId = $user->getId();
            $content.="<ol id=useradresslist >Адреса:"; 
            foreach($userData as $ud) {
                $content.="<li id='useradress-{$ud->getId()}'>"
                . "<strong>{$ud->getAddress()}</strong>"
                . "";
                
                if($j) {
                    $content.="<span class='blok'>";
                    $content.="<span class='properties propdel deleteuseraddress' rel='{$ud->getId()}'>Удалить</span>";
                    $content.="<span class='properties proptotop setuseraddress' rel='{$ud->getId()}' >Сделать по-умолчанию</span>";
                    $content.="</span>";
                } else  {
                    $j++;
                    $content.="<span class='blok gray mini'>Используется по-умолчанию</span>";
                }
                
                $content.=""
                        //. "<span class='blok mini gray'>{$ud->receiveTimestamp()}</span>"
                        . "</li>";
            }
            $content.="</ol>"; 
        }
   echo $content;   