<?php
    use Application\Resource\Resource;
?>
<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>

        <script src="//cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/qs/6.10.1/qs.min.js"></script>

        <link rel="stylesheet" href="//fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&amp;amp;display=swap" />

        <meta charset="utf-8" >
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/temp.css?' . time()))
                ->prependStylesheet($this->basePath('css/style.min.css?' . time()))
        ?>
        <script>
          var categoryTree = <?=json_encode($this->categoryTree)?>;
        </script>
        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('/js/useractions.js?' . time()))
                ->prependFile($this->basePath('/js/services.js?' . time()))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js?' . time()))
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/temp.js?' . time()))
                ->prependFile($this->basePath('js/user-modal.js?' . time()))
                ->prependFile($this->basePath('js/scripts.min.js?' . time()))
                // ->prependFile($this->basePath('js/jquery.js'))
        ?>
    </head>
    <body>
        <div id="overcoverblack" class='overcoverblack none' ></div>
        <main class="main">
            <div class="container" id="content">
                <?= 'Banzaii' ?>
                <?= $this->banzaii; ?>
                <?= $this->content ?>
            </div>
        </main>
    </body>
</html>
