<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Тест меню. Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bs.css'))
            ->prependStylesheet($this->basePath('css/treeview.css'))
            ->prependStylesheet($this->basePath('/css/dadata/suggestions.css'))
              ->prependStylesheet($this->basePath('css/saychas_z.css'))
        ?>
    <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
     <div id="header">   
         <div id="head">
             <div class="iblok" id="logo" ></div>
             <div class="menu pconly"  ></div>
             
             
         </div>
     </div>
        <!-- nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <h1>Saychas.ru</h1>
                </div>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        
                        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item "><a class="nav-link " href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="nav-item "><a class="nav-link " href="<?= $this->url('preview') ?>">Меню</a></li>
                        <li class="nav-item active"><a class="nav-link " href="<?= $this->url('provider') ?>" >Магазины</a></li>
                         <li class="nav-item "><a class="nav-link  " href="http://localhost/phpmyadmin">pma</a></li>  </ul>
                    </div>    
                    </ul>
                    </div>    
            </div>
         </nav -->

<?= $this->content ?>
    
    <?php // phpinfo()?>
    <footer>
     <p class="blokc mini">&copy; <?= date('Y') ?> saychas.ru</p>
    </footer>
<?= $this->inlineScript()
->prependFile($this->basePath('js/jquery.treeview.js'))	
->prependFile($this->basePath('js/saychas_z.js'))	
->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))	
->prependFile($this->basePath('js/jquery.treeview.async.js'))	
//->prependFile($this->basePath('js/bootstrap.min.js'))
->prependFile($this->basePath('js/jquery.js'))
?>
     </body>
</html>
