<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            
        ?>
    <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <?=$this->content?>
    </body>
</html>
