<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>

        <script src="//cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>

        <link rel="stylesheet" href="//fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&amp;amp;display=swap" />

        <meta charset="utf-8">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/custom_select.css'))
                //->prependStylesheet($this->basePath('css/style.css'))
                //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                //->prependStylesheet($this->basePath('css/bs.css'))
                ->prependStylesheet($this->basePath('css/treeview.css'))
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/nouislider.css'))
                //->prependStylesheet($this->basePath('css/saychas_z.css?' . time()))
                ->prependStylesheet($this->basePath('css/style.min.css?' . time()))
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('/js/useractions.js'))
                ->prependFile($this->basePath('/js/custom_select.js'))
                ->prependFile($this->basePath('/js/services.js'))
                ->prependFile($this->basePath('/js/nouislider.min.js'))
                ->prependFile($this->basePath('/js/nivo.slider.js'))
                ->prependFile($this->basePath('js/jquery.treeview.js'))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))
                ->prependFile($this->basePath('js/jquery.treeview.async.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/scripts.min.js'))
// ->prependFile($this->basePath('js/jquery.js'))
        ?>
    </head>
    <body>
        <?= (!$this->legalUser) ? $this->partial("/application/common/user-modal-win", ["param" => []]) : "" ?>
        <?= $this->partial("/application/common/service-modal-window", ["param" => []]) ?>
        <div class="overcover"></div>
        <div id="overcoverblack" class='overcoverblack none' ></div>
        <div id="quicktop" class='none' ></div>



        <div id="lefmobiletpanel">
            <div id="lefmobiletpanelclose" ></div>
            <div id="lefmobiletpanelcontent"  class="blokc" ><div class=logo ></div>

                <div class='iblokok' id=supermenuinside>

                    <ul id="tree" class="tree treeview" style=""><h3><?= Application\Resource\Resource::THE_CATALOG ?></h3>
                        <?= $this->catalogCategoties ?>
                    </ul>

                </div >
            </div >
            <!---->
        </div>

        <header class="header">
            <?= $this->partial("/application/index/partials/main-layout/header-menu", ["menu" => []]) ?>
            <div class="container">

                <div id="catalogbutton" class="catalogshow">
                    <div class=catalogbutton >
                        <div class=mobile_nav_icon></div>
                        <?= Application\Resource\Resource::THE_CATALOG ?>
                    </div>
                </div>

                <div class="iblok" id="logo" ></div>

                <div id="topservice">

                    <div class='pw-contentblock cblock-2' id="searchblock">
                        <?= $this->partial("/application/index/partials/main-layout/search-block", ["addresses" => $this->addresses, "addressesJson" => $this->addressesJson]) ?>
                    </div>

                    <div class='pw-contentblock cblock-2 nopadding'>
                        <div  style="  " class="blokl nopadding" id="searchpanel">
                            <?= $this->partial("/application/index/partials/main-layout/user-address-in-layout", ["addresses" => $this->addresses, "addressesJson" => $this->addressesJson]) ?>
                        </div>
                    </div>

                    <div class='iblok' id="profileblock">
                        <?= $this->partial("/application/index/partials/main-layout/top-user-profile-block", ["userLegal" => $this->userLegal, "username" => $this->username]) ?>
                        <?= $this->partial("/application/index/partials/main-layout/top-basket-block", ["addressLegal" => $this->addressLegal]) ?>
                    </div>
                
                </div>
                
                <?= $this->partial("/application/common/quick-menu", ["menu" => $this->mainMenu]) ?>
            </div>
        </header>

        <main class="main">
            <div class="container" id="content">
                <?= $this->content ?>
            </div>
        </main>


        <div id="bascetbottomblok" class='none'>
            <div class='close'></div>
            <div class="content"></div>
        </div>

        <?= $this->partial("/application/index/partials/main-layout/footer", ["content" => [] /* $this->footer */]) ?>

    </body>
</html>
