<?php
    use Application\Resource\Resource;
?>
<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>

        <script src="//cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/qs/6.10.1/qs.min.js"></script>

        <link rel="stylesheet" href="//fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&amp;amp;display=swap" />

        <meta charset="utf-8" >
        <meta name="format-detection" content="telephone=no">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/dadata/suggestions.css'))
                ->prependStylesheet($this->basePath('css/temp.css?' . time()))
                ->prependStylesheet($this->basePath('css/style.min.css?' . time()))
        ?>
        <script>
          var categoryTree = <?=json_encode($this->categoryTree)?>;
        </script>
        <!-- Scripts -->
        <?= $this->headScript() ?>

        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('/js/useractions.js?' . time()))
                ->prependFile($this->basePath('/js/services.js?' . time()))
                ->prependFile($this->basePath('js/saychas_z.js?' . time()))
                ->prependFile($this->basePath('js/dadata/jquery.suggestions.js?' . time()))
                //->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/temp.js?' . time()))
                ->prependFile($this->basePath('js/user-modal.js?' . time()))
                ->prependFile($this->basePath('js/scripts.min.js?' . time()))
                // ->prependFile($this->basePath('js/jquery.js'))
        ?>
    </head>
    <body>
        <div class="overcover">
          <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        </div>
        <div id="overcoverblack" class='overcoverblack none' ></div>

        <header class="header">
            <?= $this->partial("/application/index/partials/main-layout/header-menu", ["menu" => []]) ?>
            <div class="container">
                <div class="header__mid">
                    <div class="header__mid-left">
                        <div class="header__catalog">
                            <input type="checkbox" id="burger" />
                            <label class="header__burger catalogshow catalogbutton" for="burger">
                                <span class="header__burger-icon">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </span>
                                <span><?=Resource::THE_CATALOG ?></span>
                            </label>
                            <nav class="cats" id="cats">
                              <div class="cats__left">
                                <div v-for="(category, idx) in categoryTree" class="cats__item" :class="{active: (idx == currentCat)}">
                                  <a :href="'/catalog/' + category.url" class="cats__parent" @mouseover="currentCat = idx">{{ category.title }}</a>
                                </div>
                              </div>
                              <div class="cats__right">
                                <div v-for="(category, idx) in categoryTree">
                                  <div v-show="idx == currentCat" class="cats__children">
                                    <ul v-for="categoryChild in category.children">
                                      <li>
                                        <a :href="'/catalog/' + categoryChild.url">{{ categoryChild.title }}</a>
                                      </li>
                                      <div v-if="categoryChild.children">
                                        <li v-for="categoryChildChild in categoryChild.children.slice(0, 5)">
                                          <a :href="'/catalog/' + categoryChildChild.url">{{ categoryChildChild.title }}</a>
                                        </li>
                                      </div>
                                      <li v-if="categoryChild.children && categoryChild.children.length > 6">
                                          <a class="cats__all" :href="'/catalog/' + categoryChild.url"><?=Resource::THE_ALL_PRODUCTS ?></a>
                                      </li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </nav>
                        </div>
                        <div class="header__logo">
                            <picture>
                                <source srcset="/img/logo-mobile.svg" media="(max-width: 767px)" />
                                <source srcset="/img/logo.svg" />
                                <img srcset="/img/logo.svg" alt="Say:час логотип" />
                            </picture>
                        </div>
                        <div class="header__search" id="searchblock">
                           <?= $this->partial("/application/index/partials/main-layout/search-block", ["addresses" => $this->addresses, "addressesJson" => $this->addressesJson]) ?>
                        </div>
                        <div class="header__address">
                           <?= $this->partial("/application/index/partials/main-layout/user-address-in-layout", ["addresses" => $this->addresses, "addressesJson" => $this->addressesJson]) ?>
                        </div>
                    </div>
                    <div class="header__icons" id="profileblock">
                        <?= $this->partial("/application/index/partials/main-layout/top-user-profile-block", ["userLegal" => $this->userLegal, "userinfo" => $this->userinfo]) ?>
                        <?php // = $this->partial("/application/index/partials/main-layout/top-user-profile-block", ["userLegal" => $this->userLegal, "username" => $this->userinfo["name"]]) ?>
                        <?= $this->partial("/application/index/partials/main-layout/top-basket-block", ["addressLegal" => $this->addressLegal, 'count' => $this->basketProductsCount]) ?>
                    </div>
                </div>
                <?= $this->partial("/application/common/quick-menu", ["menu" => $this->mainMenu]) ?>
            </div>
        </header>

        <main class="main">
            <div class="container" id="content">
                <?= $this->content ?>
            </div>
        </main>


        <div id="basketbottom" class='basketbottom'>
            <div class='basketbottom__close'></div>
            <div class="basketbottom__content"></div>
        </div>

        <?= $this->partial("/application/index/partials/main-layout/footer", ["content" => [] /* $this->footer */]) ?>
    </body>
</html>
