<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bs.css'))
            ->prependStylesheet($this->basePath('css/treeview.css'))
            ->prependStylesheet($this->basePath('/css/dadata/suggestions.css'))
              ->prependStylesheet($this->basePath('css/saychas_z.css?'.time()))
        ?>
    <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="overcover"></div>
        
        <div id="header" class="blokc">   
            <div id="head">
                <!-- div id="mobile_nav_icon"><div class="mobile_nav_icon"></div></div -->
            <div class="iblok" id="logo" ></div>
            <!-- span class="" style="border:1px solid red" -->
                    
                    <DIV  style="  " class="iblokl" id="searchpanel">         
                        <input type=text 
                                id='useraddress'  
                               placeholder='Укажи адрес доставки'   
                               pattern="[A-Za-zА-Яа-яЁё]{3,}"  required 
                               accept=""
                               class='pn-text iblok' 
                        />
                        <div id="useradesserror" class="errorblock none"></div>
                    <div class="searchpanelclose"></div></DIV>
		  
            <div class='geo16 open-user-address-form user_address_set' id="uadress" ><?=$userAddressHtml?></div>
             <div class="iblok"><?= $this->addressform ?></div>
                <div style='float:right'>
                   <a class="navlink " href="<?= $this->url('home') ?>">Home</a>
                   <a class="navlink" href="<?= $this->url('preview') ?>">Меню</a>
                   <a class="navlink" href="<?= $this->url('provider') ?>" >Магазины</a>
                   <a class="navlink" href="<?= $this->url('catalog') ?>" >Каталог</a>
                   <a class="navlink" href="<?= $this->url('test-repos') ?>" >Banzaii</a>
                   <a class="navlink" href="/phpmyadmin" >Sql</a>
                </div>
            </div>
        </div> 
        <div class="full-wrap"><div id="content">                          
        <?= $this->content ?>                    
        </div></div>
        <footer>
         <p class="blokc mini">&copy; <?= date('Y') ?> saychas.ru</p>
        </footer>
<?= $this->inlineScript()
->prependFile($this->basePath('js/jquery.treeview.js'))	
->prependFile($this->basePath('js/saychas_z.js?'.time()))	
->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))	
->prependFile($this->basePath('js/jquery.treeview.async.js'))	
//->prependFile($this->basePath('js/bootstrap.min.js'))
->prependFile($this->basePath('js/jquery.js'))
?>
    </body>
</html>
