<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Тест меню. Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bs.css'))
            ->prependStylesheet($this->basePath('css/treeview.css'))
            ->prependStylesheet($this->basePath('/css/dadata/suggestions.css'))
        ?>
    <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <h1>Saychas.ru</h1>
                </div>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <!--? //php echo $this->partial('application/index/partials/menu1'); ?-->
                        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item  "><a class="nav-link" href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="nav-item active"><a class="nav-link " href="<?= $this->url('preview') ?>">Меню</a></li>
                        <li class="nav-item "><a class="nav-link" href="<?= $this->url('provider') ?>" >Магазины</a></li>
                         <li class="nav-item "><a class="nav-link" href="http://localhost/phpmyadmin">pma</a></li>
                      </ul>
                    </div>    
                    </ul>
                    </div>    
            </div>
         </nav>
<div class="container" styele="max-width:1400px">	
    <div class="card-deck"> 
       <div class="card">
        <h2 class="card-header">Test Dadata</h2>
        <div class="card-body">
            <div class="container" >
	
             
                              <input id="address" name="suggestions"  placeholder="укажи адрес доставки"/>
                 <div id="dadataanswer" style="font-size:12px; color:#ccc"></div>
            </div>  
        </div>
       </div> 
    <div class="card" id="ycard" style="display:none;">
        <!-- div style=heignt:500px; -->
   <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&mode=debug" type="text/javascript"></script>
    <script type="text/javascript">
        ymaps.ready(init);
        function init(){
         myMap = new ymaps.Map("map", {
                center: [55.71, 37.68],
                zoom: 7
            });
        }
		  
    </script>   
        
           <div class="card-body" id="map">
   
            <!-- 'geo_lat' => "55.7132713"  'geo_lon' => "37.6860004" -->
            <div id="geocoords"></div>
           </div>
       </div> 
	   <!-- /div--> 
    </div>        
 <p><hr/></p>
<div class="card-deck">        
      
        <div class="card">
        <h2 class="card-header">Test POST 1C=>Site</h2>
        <div class="card-body">
            <div class="container" >
		 <div id="ajaxanswer2"></div>
                 <!-- form method="post" id="formajax2"  ><input name=name val="" placeholder="имя переменной" style="margin:5px 0; padding:4px" --><br/>
                 <textarea ID=textarea name=value val="" placeholder="значение" style="margin:5px 0;padding:4px; width:96%; display:block" >[{"id": "00003","name": "Xiaomi "},{"id": "00003","name": "Xiaomi "}]</textarea> 
				 </form>
                 <input type="button" id="sendajax2"   class="btn btn-primary" value='Иммитировать запрос из  1C' />
            </div>  
        </div>
        </div>
		
		<div class="card">
        <h2 class="card-header">Test POST Site=>1C </h2>
        <div class="card-body">
            <div class="container" >
		 <div id="ajaxanswer"></div>
                 <form method="post" id="formajax" ><input name=name val="" placeholder="имя переменной" style="margin:5px 0; padding:4px"><br/>
                 <input name=value val="" placeholder="значение" style="margin:5px 0;padding:4px" ><br/> </form>
                 <input type="button" id="sendajax"   class="btn btn-primary" value='Отправить запрос в 1C' />
            </div>  
        </div>
        </div>
	</div>
<div class="card-deck"> 	
	   <div class="card">
             <h2 class="card-header">Каталог</h2>
             <div class="container">
		 <ul id="tree">
                     <?= $this->content ?>
		 </ul>	
                 </div>  
          </div>  

 
</div>
	</div>    
    <hr>
    <footer>
     <p class="blokc mini">&copy; <?= date('Y') ?> saychas.ru</p>
    </footer>
        
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery.treeview.js'))	
        ->prependFile($this->basePath('js/saychas_z.js'))
        ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))	
        ->prependFile($this->basePath('js/jquery.treeview.async.js'))	
		//->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.js'))
        ?>
    </body>
</html>
