<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?><?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Тест меню. Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/treeview.css'))
            ->prependStylesheet($this->basePath('/css/dadata/suggestions.css'))
        
        
        	
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <h1>Saychas.ru</h1>
                </div>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <!--? //php echo $this->partial('application/index/partials/menu1'); ?-->
                        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item "><a class="nav-link" href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="nav-item active"><a class="nav-link active" href="<?= $this->url('preview') ?>">Меню</a></li>
                         <li class="nav-item active"><a class="nav-link active" href="http://localhost/phpmyadmin">pma</a></li>
                       
       
                    </ul>
                    </div>    
                    </ul>
                    </div>    
            </div>
            
        </nav>
<div class="container" styele="max-width:1200px">	
    <div class="card-deck"> 
       <div class="card">
        <h2 class="card-header">Test Dadata</h2>
        <div class="card-body">
            <div class="container" >
	
             
                              <input id="address" name="suggestions"  placeholder="укажи адрес доставки"/>
                 <div id="dadataanswer" style="font-size:12px; color:#ccc"></div>
            </div>  
        </div>
       </div> 
    <div class="card" id="ycard" style="display:none;">
        <!-- div style=heignt:500px; -->
   <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&mode=debug" type="text/javascript"></script>
    <script type="text/javascript">
        ymaps.ready(init);
        function init(){
         myMap = new ymaps.Map("map", {
                center: [55.71, 37.68],
                zoom: 7
            });
        }
		  
    </script>   
        
           <div class="card-body" id="map">
   
            <!-- 'geo_lat' => "55.7132713"  'geo_lon' => "37.6860004" -->
            <div id="geocoords"></div>
           </div>
       </div> 
	   <!-- /div--> 
    </div>        
 <p><hr/></p>
<div class="card-deck">        
         <div class="card">
             <h2 class="card-header">Каталог</h2>
             <div class="container">
		 <ul id="tree">
                     <?= $this->content ?>
		 </ul>	
                 </div>  
          </div>  
        <div class="card">
        <h2 class="card-header">Test POST 1C=>Site</h2>
        <div class="card-body">
            <div class="container" >
		 <div id="ajaxanswer2"></div>
                 <form method="post" id="formajax2"  ><input name=name val="" placeholder="имя переменной" style="margin:5px 0; padding:4px"><br/>
                 <textarea name=value val="" placeholder="значение" style="margin:5px 0;padding:4px" ></textarea> 
				 </form>
                 <input type="button" id="sendajax2"   class="btn btn-primary" value='иммитировать запрос из  1C' />
            </div>  
        </div>
        </div>
		
		<div class="card">
        <h2 class="card-header">Test POST Site=>1C </h2>
        <div class="card-body">
            <div class="container" >
		 <div id="ajaxanswer"></div>
                 <form method="post" id="formajax" ><input name=name val="" placeholder="имя переменной" style="margin:5px 0; padding:4px"><br/>
                 <input name=value val="" placeholder="значение" style="margin:5px 0;padding:4px" ><br/> </form>
                 <input type="button" id="sendajax"   class="btn btn-primary" value='отправить запрос в 1C' />
            </div>  
        </div>
        </div>
		
		<!-- comment -->
     

</div>
</div>    
            <hr>
            <footer>
                <p class="blokc mini">&copy; <?= date('Y') ?> saychas.ru</p>
            </footer>
        
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery.treeview.js'))	
        ->prependFile($this->basePath('js/dadata/jquery.suggestions.js'))	
        ->prependFile($this->basePath('js/jquery.treeview.async.js'))	
	->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
        <script type="text/javascript">
            
        
   $(function() {
	   
	                            
       //$(document).mousedown(function(){return false});
       $("#dadataanswer").slideUp();
       $("#address").click(function(){$("#dadataanswer").slideUp(); $("#ycard").fadeOut();})
       $("#address").suggestions({
                            token: "af6d08975c483758059ab6f0bfff16e6fb92f595",
                            type: "ADDRESS",
                            /* Вызывается, когда пользователь выбирает одну из подсказок */
                            onSelect: function(suggestion) {
                             
                             $("#ycard").fadeIn();
                             $("#dadataanswer").stop().html("<pre>"+print_r(suggestion)+"</pre>").slideDown();
                             myMap.setCenter([suggestion.data.geo_lat,suggestion.data.geo_lon],16)
							 //var myCollection = new ymaps.GeoObjectCollection({}, {preset: "'islands#redPersonIcon'",    strokeWidth: 4,    geodesic: false	});
                            
		 
                             //ymaps.removeAllOverlays();//
							//clearOverlays(placemark);
						   //myMap.geoObjects.remove(placemark);
							 //myMap.geoObjects.add(placemark);
                            // myMap.geoObjects.add(myCollection);
						   
						   var  placemark = new ymaps.Placemark([suggestion.data.geo_lat,suggestion.data.geo_lon], { balloonContent: 'я тут'}, )
						   
						   myMap.geoObjects.each(function (geoObject) {
									if (geoObject instanceof ymaps.Placemark) {
										myMap.geoObjects.remove(geoObject);  
									//console.log(geoObject.geometry.getCoorditanes())
								}
							});
						   
						    myMap.geoObjects.add(placemark);  
						   //myCollection.removeAll(); 
						   //myCollection.add(placemark);
					  //console.log(myCollection);
						   
                  $("#geocoords").html(suggestion.data.geo_lat+","+suggestion.data.geo_lon);
                              //console.log(suggestion.data.geo_lat);
                              //console.log(suggestion.data.geo_lon);
                            }
             });
                        
            $("#tree").treeview({
                  persist: "location",
                  collapsed: true,
                animated: "medium",
                
            });
           
        $("#sendajax").click(function(){
            var dataString = $("#formajax").serialize();
            $.ajax({	
               // beforeSend : function (){ $("#overload").stop().show(); },
               
            url: "/ajax/",
               // url: "http://SRV02:8000/sc/hs/site/get_product",
		type:'POST', 
		cache: false,	
		data: dataString,
		success: function(data){
                    $("#ajaxanswer").html(data);
		},
                error: function (xhr, ajaxOptions, thrownError) {
			$("#ajaxanswer").html("Ошибка соединения, попробуйте повторить попытку позже."+"\r\n " + xhr.status +" "+ thrownError );
		}
            })
       })
	   
	   
	   $("#sendajax2").click(function(){
            var dataString = $("#formajax2").serialize();
            $.ajax({	
               // beforeSend : function (){ $("#overload").stop().show(); },
               
            url: "/receive",
               // url: "http://SRV02:8000/sc/hs/site/get_product",
		type:'POST', 
		cache: false,	
		data: dataString,
		success: function(data){
                    $("#ajaxanswer2").html(data);
		},
                error: function (xhr, ajaxOptions, thrownError) {
			$("#ajaxanswer2").html("Ошибка соединения, попробуйте повторить попытку позже."+"\r\n " + xhr.status +" "+ thrownError );
		}
            })
       })
	   
        
        
    });
    function print_r(arr, level) {
    var print_red_text = "";
    if(!level) level = 0;
    var level_padding = "";
    for(var j=0; j<level+1; j++) level_padding += "    ";
    if(typeof(arr) == 'object') {
        for(var item in arr) {
            var value = arr[item];
            if(typeof(value) == 'object') {
                print_red_text += level_padding + "'" + item + "' :\n";
                print_red_text += print_r(value,level+1);
    } 
            else 
                print_red_text += level_padding + "'" + item + "' => \"" + value + "\"\n";
        }
    } 

    else  print_red_text = "===>"+arr+"<===("+typeof(arr)+")";
    return print_red_text;
}
    
	</script>
    </body>
</html>
