<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?><?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Тест меню. Saychas.ru')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/treeview.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <h1>Saychas.ru</h1>
                </div>
               <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <!--? //php echo $this->partial('application/index/partials/menu1'); ?-->
                        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item "><a class="nav-link" href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="nav-item active"><a class="nav-link active" href="<?= $this->url('preview') ?>">Меню</a></li>
                       
       
                    </ul>
                    </div>    
                    </ul>
                    </div>    
            </div>
            
        </nav>
<div class="container" styele="max-width:1200px">	
<div class="card-deck">        
         <div class="card">
             <h2 class="card-header">Каталог</h2>
             <div class="container">
		 <ul id="tree">
                     <?= $this->content ?>
		 </ul>	
                 </div>  
          </div>  
        <div class="card">
        <h2 class="card-header">Test ajax</h2>
        <div class="card-body">
            <div class="container" >
		 <div id="ajaxanswer"></div>
                 <form method="post" id="formajax" ><input name=name val="" placeholder="имя переменной" style="margin:5px 0; padding:4px"><br/>
                 <input name=value val="" placeholder="значение" style="margin:5px 0;padding:4px" ><br/> </form>
                 <input type="button" id="sendajax"   class="btn btn-primary" value='отправить запрос в 1C' />
            </div>  
        </div>
    </div> 
</div>
</div>
    
            <hr>
            <footer>
                <p class="blokc mini">&copy; <?= date('Y') ?> saychas.ru</p>
            </footer>
        
        <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery.treeview.js'))	
        ->prependFile($this->basePath('js/jquery.treeview.async.js'))	
	->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>
        <script type="text/javascript">
   $(function() {
            $("#tree").treeview({
                  persist: "location",
                  collapsed: true,
                animated: "medium",
                
            });
           
        $("#sendajax").click(function(){
            var dataString = $("#formajax").serialize();
            $.ajax({	
               // beforeSend : function (){ $("#overload").stop().show(); },
               
            url: "/ajax/",
               // url: "http://SRV02:8000/sc/hs/site/get_product",
		type:'POST', 
		cache: false,	
		data: dataString,
		success: function(data){
                    $("#ajaxanswer").html(data);
		},
                error: function (xhr, ajaxOptions, thrownError) {
			$("#ajaxanswer").html("Ошибка соединения, попробуйте повториить попытку позже."+"\r\n " + xhr.status +" "+ thrownError );
		}
            })
       })
        
        
    });
	</script>
    </body>
</html>
