<div class="fluid-container">
    <div class="row">
        <div class="col-lg-4 col-md-12" >
            <?php
                echo '<pre>';
                print_r($stores);
                echo '</pre>';
            ?>
        </div>
        <div class="col-lg-4 col-md-12 <?php //bg-success  ?>">
            <?= $this->partial('control-panel/index/partials/stores/list', ['table' => $table, 'stores' => $stores,]); ?>
        </div>
        <div class="col-lg-4 col-md-12 <?php // bg-info  ?>">
            <?= $this->partial('control-panel/index/partials/stores/edit-form', ['row' => $table[0]]); ?>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-sm-12 <?php //bg-primary  ?>">
            <?= $this->partial('control-panel/index/partials/stores/time-table'); ?>
        </div>
    </div>
</div>
