<div class="fluid-container">
    <div class="row">
        <div class="col-sm-6 <?php //bg-success  ?> min-height-100">
            <?= $this->partial('control-panel/index/partials/products/list', ['products' => $products]); ?>
        </div>
        <div class="col-sm-6 <?php //bg-info  ?> min-height-100">
            <?= $this->partial('control-panel/index/partials/products/edit-form'); ?>
        </div>
    </div>
</div>
