<div class='pw-contentblock cblock-1' id='paycardblok'>
    <div class='contentpadding'>
    
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio zach  black loadpayinfo' rel='paynew' for='paynewoff'> 
                    <b> 
                         <span class='iblok valign-middle '>Оплата с привязанной карты </span> 
                       
					</b>
		</div>
             
                <span class='lableinfo text'><?=$cardinfo ?>1</span>
                
                 
             </div>
        </div>
        
        
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio black loadpayinfo' rel='paynew' for='paynewon'> 
                     <b>
                         <span class='iblok valign-middle '>Оплата новой картой</span> 
                     </b>
			</div>
                <span class='blok gray text' >
                    Расплачиватесь — мы запомним данные вашей карты, что бы не вводить её в следущий раз
                </span>
               
                
            </div>
            <input type="checkbox" name='paycard' class='relradiopaynew none fltrcheckpaynewon' value='0' >
            <input type="checkbox" name='paycard' class='relradiopaynew none fltrcheckpaynewoff' value='1' checked  >
        </div>
    </div>
</div>