<div class='pw-contentblock cblock-1'>
    <div class='pw-contentblock cblock-6'>
        <div class='contentpadding'><h2>Доставка</h2></div>
    </div>
    <div class='pw-contentblock cblock-4'>
        <!--div class='contentpadding blokr' style='padding-top:16px;'><a href=# class="redlink">Изменить</a></div-->
    </div>
    <div class='contentpadding' id='basketuserdata'>
        <div class="char-row">
            <span class="char-title"><span>Адрес доставки </span>
            </span><span class="char-value">
                <input type="text" id="basketuseradress"  value="<?= $basketUser['address'] ?>" class="lableinfo" name=basketuseradress" >
                <span class="mini red blok" id="basketuseradresserror"></span>    
                <span class="mini gray">При изменении адреса изменяется доступность товаров в корзине</span>
            </span>
        </div>    

        <div class="char-row">
            <span class="char-title"><span>Получатель </span>
            </span><span class="char-value"><div class="contentpaddingbox contentpaddinguserbox">   
                    <div class="basketrow">
                        <div class="basketcol imageproduct">
                            <div class="avatar"><?=mb_substr(trim($basketUser['name']),0,1)?></div>
                        </div>
             <div class="basketcol titleuser">
                <b><?= $basketUser['name'] ?></b> <div class='blok'><?= $basketUser['phoneformated'] ?></div>
            </div>
                    <div class="basketcol exituser">
                        
                            <div class="contentpadding"><a href="/clear-user-data" class=""><img src="/img/saychas-zero.svg" class="grayscale contentpadding">Выход</a></div>
                        
                    </div>
                    
                </div>
                </div>
            </span>
            
        </div>
        <div class="char-row">
            <span class="char-title"><span>Комментарий курьеру </span>
            </span><span class="char-value">
                <input type="text" id="basketusercomment"   class="lableinfo" placeholder="О чем должен знать курьер?">
                <span class="mini gray"></span>

            </span>
        </div>
    </div>
</div>