<div class='contentpadding'>
    <div class='paybox' >
        <div class='contentpadding'>
            <div class='delevery-item delevery-door' > 
                <b class='blok'>Доставка</b>
                <div class='blok'>Информация о времени доставки</div>
                <div class='blok'>Адрес доставки. Например: Угрешская улица, д.2 стр. 34, офис 333 </div>
            </div>

            <div class='delevery-item delevery-self' > 
                <b class='blok'>Самовывоз</b>
                <div class='blok'>Информация о времени актуальности</div>
                <div class='blok'>Информация о магазинах </div>
            </div>

            <div class='delevery-item delevery-self' > 
                <b class='blok'>Оплата</b>
                <div class='blok'>Информация о типе оплаты</div>
                <div class='blok'>Пример: Онлайн, картой <span class="red">5213 2487 **** 0817&darr;</span></div>
            </div>


        </div>
        <div class='volna' ></div>  
        <div class='contentpadding'>
            <h2 class='blok price'>28 123&#8381; 
                <span class='oldprice'>32 123&nbsp;&#8381;</span>
            </h2>
            <div class='char-row'>
                <span class='char-title'>
                    <span>Товары(#)</span>
                </span><span class=char-value >
                    <span>28 000&#8381; <tag class='oldprice'>32 000&#8381;</tag> </span>
                </span>
            </div>
            <div class='char-row'>
                <span class='char-title'>
                    <span><strong>Доставка за час</strong></span>
                </span><span class=char-value >
                    <span><strong>123&#8381;</strong></span>
                </span>
            </div>
            <div class='char-row'>
                <span class='char-title'>
                    <span>Самовывоз</span>
                </span><span class=char-value >
                    <span>0&#8381;</span>
                </span>
            </div>

            <div class='contentpadding'>
                <div class=paybutton  >перейти к оплате</div>
            </div>

            <div class='contentpadding'>
                <div class='gray mini'  >Нажимая на кнопку, вы соглашаетесь с <a href=# class="red" >Условиями обработки перс. данных</a>, а также с <a href=# class="red" >Условиями продажи</a></div>
            </div>

        </div>    
    </div>
</div>