<div class='pw-contentblock cblock-1' id='basketordermerge'>
    <div class='contentpadding'>
    
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio zach  black' rel='dostmerge' for='dostmergeoff'> 
                    <b> 
                         <span class='iblok valign-middle '>Доставки из 3 магазинов </span> 
                         <span class='iblok valign-middle saychas'>за 1 час</span> 
                         <span class='iblok valign-middle '> &mdash;&nbsp;999&nbsp;₽  </span> 
					</b>
		</div>
                <span class='blok gray text'>
                    Для каждого магазина мы назначим отдельного курьера, 
                    тем самым за час вы получите все свои товары в 3 доставках
                </span>
                <span class='lableinfo text'>c 15:00 до 16:00</span>
                
                 
             </div>
        </div>
        
        
        <div class='pw-contentblock cblock-2'>
            <div class='contentpadding'>
                <div class='radio black' rel='dostmerge' for='dostmergeon'> 
                     <b>
                         <span class='iblok valign-middle '>Объеденить заказы </span> 
                         <span class='iblok valign-middle saychas'>за 1 часа</span> 
                         <span class='iblok valign-middle '> &mdash;&nbsp;333&nbsp;₽  </span> 
                     </b>
		</div>
                <span class='blok gray text' >
                    На каждые 3 магазина мы назначим по курьеру, 
                    тем самым вы получите все свои товары 
                    в 1 доставке (правда это будет дольше)
                </span>
                <span class='lableinfo text'>c 15:00 до 18:00</span>
                
            </div>
            <input type="checkbox" name='ordermerge' class='relradiodostmerge none fltrcheckdostmergeon' value='1' >
            <input type="checkbox" name='ordermerge' class='relradiodostmerge none fltrcheckdostmergeoff' value='0' checked  >
        </div>
    </div>
</div>