<?php foreach ($param as $product):
        $enable = ($product['availble']>0 and !$provider_disable);
        $disabled = ($enable)?"":" disabled ";
?>

<li class="cart__product <?=($enable) ? 'cart__product--na':''?>" id="basketrow-<?=$product['id']?>">
  <div class="cart__checkbox">
    <?php if($enable) :?>
      <label class="checkbox provider-<?=$provider?>" rel='<?=$product['id']?>' provider='<?=$provider?>'>
        <input type="checkbox" checked name="products[<?=$product['id']?>][count]" value="<?=$product['count']?>"
               class="none povidercheck-<?=$provider ?> product-<?=$product['id']?>  allallcheck " id="countprhidden-<?=$product['id']?>">
        <input type="checkbox" checked  name="products[<?=$product['id']?>][price]" value="<?=$product['price']?>"
               class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
               />
        <input type="checkbox" checked  name="products[<?=$product['id']?>][store]" value="<?=$product['store']?>"
               class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
               />
        <span class="checkbox__check"></span>
      </label>
    <?php endif;?>
  </div>
  <div class="cart__product-img">
    <img src="<?=$this->imagePath('product')?>/<?=$product['image']?>" />
  </div>
  <a class="cart__product-title" href="/product/<?=$product['id']?>">
    <?=$product['title']?>
  </a>
  <div>
    <div class="cart__product-del deleteproduct" rel='<?=$product['id']?>' provider='<?=$provider?>'>
      <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
      </svg>
    </div>
  </div>
  <div class="cart__product-info">
    <?php if($enable) :?>
      <div class="cart__product-quantity" id="countproduct-<?=$product['id']?>">
        <button class="cart__product-minus disabled"></button>
        <input type="number" value="1" />
        <button class="cart__product-plus"></button>
      </div>
      <div class="cart__product-price">
          <div class="cart__product-price-current"><?=number_format(((int)($product['price']*$product['count'])/100), 0, ',', '&nbsp;');?> ₽</div>
          <?if ($product['oldprice']) ?>
            <div class="cart__product-price-old"><?=number_format(((int)$product['oldprice']/100), 0, ',', '&nbsp;')?> ₽</div>
          <? endif; ?>
      </div>
    <?php else:?>
      <div class="cart__product-na" id="priceproduct-<?=$product['id']?>">Товара нет в наличии</div>
    <?php endif;?>
  </div>
</li>

<!-- <div class='blok basketrow  basketrowproduct  ' id="basketrow-<?=$product['id']?>">
        <div  class='basketcol<?=$disabled?>  check'>
<?php if($enable) :?>
            <div class='poroductcounme nopub checkallprovider provider-<?=$provider?>  allall zach ' rel='<?=$product['id']?>' provider='<?=$provider?>' ></div>
            <input type="checkbox" checked name="products[<?=$product['id']?>][count]" value="<?=$product['count']?>"
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?>  allallcheck " id="countprhidden-<?=$product['id']?>">
            <input type="checkbox"  checked  name="products[<?=$product['id']?>][price]" value="<?=$product['price']?>"
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
                   />
            <input type="checkbox"  checked  name="products[<?=$product['id']?>][store]" value="<?=$product['store']?>"
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
                   />
<?php endif;?>
        </div>

        <div  class='basketcol<?=$disabled?>  imageproduct '>
            <img src="<?=$this->imagePath('product')?>/<?=$product['image']?>" alt=""
                 class="product-page-image productimage1"  title="">
        </div>

        <div  class='basketcol<?=$disabled?>  titleproduct product'>
           <?=$product['title']?>
        </div>
<?php if(!$provider_disable) :?>
        <div  class='basketcol<?=$disabled?>  deleteproduct' rel='<?=$product['id']?>' provider='<?=$provider?>' >
            <img src="/img/saychas-zero.svg" class="grayscale"   />
        </div>
<?php if($enable) :?>
        <div  class='basketcol  countproduct' id="countproduct-<?=$product['id']?>" >
            <span><div class="countproductminus <?=($product['count'] < 2)?"disabled":""?>" rel='<?=$product['id']?>' >
            </div></span><div class="countproductnum " id="countproductnum-<?=$product['id']?>" max="<?=$product['availble']?>"><?=$product['count']?>
            </div><div class="countproductplus <?=($product['count'] >= $product['availble'])?"disabled":""?>" rel='<?=$product['id']?>'></div>

        </div>

        <div  class='basketcol<?=$disabled?>  priceproduct' >
            <span class="price" ><tag id="priceproduct-<?=$product['id']?>"><?=number_format(((int)($product['price']*$product['count'])/100), 0, ',', '&nbsp;');?></tag>&nbsp;₽ </span>
            <?=(false and $product['oldprice'])
                ?'<span class="oldprice">'.number_format(((int)$product['oldprice']/100), 0, ',', '&nbsp;').'&nbsp;₽</span>'
                :''
            ?>
        </div>
<?php  else : ?>
        <div  class='basketcol<?=$disabled?>  priceproduct disabled' id="priceproduct-<?=$product['id']?>">
            Товара нет в наличии
        </div>
<?php endif;?>
<?php endif;?>
        <div  class='basketcol<?=$disabled?>  addtofavproduct'>
            <img src="/img/saychas-zero.svg" class="favtprop" rel='<?=$product['id']?>'  />
        </div>

 </div> -->

<?php endforeach;?>
