<div class='pw-contentblock cblock-1'>
    <div class='pw-contentblock cblock-6'>
        <div class='contentpadding'><h2>Доставка</h2></div>
    </div>
    <div class='pw-contentblock cblock-4'>
        <div class='contentpadding blokr' style='padding-top:16px;'><a href=# class="redlink">Изменить</a></div>
    </div>
     
    <div class='contentpadding' id='basketuserdata'>
        
        <div class="char-row">
            <span class="char-title"><span>Адрес доставки </span>
            </span><span class="char-value"><span>Самая длинная Угрешская улица в городе Москве, дом 22 строение 33</span></span>
        </div>    
        
        <div class="char-row">
            <span class="char-title"><span>Получатель </span>
            </span><span class="char-value"><span>Александр Григорьевич Сыропупкин-Кобылин <div class='blok'>+7 (913)214 66 66</div></span></span>
        </div>
        
        <div class="char-row">
            <span class="char-title"><span>Комменатрий курьеру </span>
            </span><span class="char-value"><span>Перед подъездом открытый люк! Домофон не работает. Предварительно позвонить</span></span>
        </div>
        
    </div>
</div>