<?php foreach ($param as $product):
        $enable = ($product['availble']>0 and !$provider_disable);
        $disabled = ($enable)?"":" disabled ";
?>

<div class='blok basketrow  basketrowproduct  ' id="basketrow-<?=$product['id']?>">
        <div  class='basketcol<?=$disabled?>  check'>
<?php if($enable) {?>
            <div class='poroductcounme nopub checkallprovider provider-<?=$provider?>  allall zach ' rel='<?=$product['id']?>' provider='<?=$provider?>' ></div>
            <input type="checkbox" checked name="products[<?=$product['id']?>][count]" value="<?=$product['count']?>"  
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?>  allallcheck " id="countprhidden-<?=$product['id']?>">
            <input type="checkbox"  checked  name="products[<?=$product['id']?>][price]" value="<?=$product['price']?>" 
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
                   />
            <input type="checkbox"  checked  name="products[<?=$product['id']?>][store]" value="<?=$product['store']?>" 
                   class="none povidercheck-<?=$provider ?> product-<?=$product['id']?> allallcheck"
                   />
<?php }?>
        </div>    

        <div  class='basketcol<?=$disabled?>  imageproduct '>
            <img src="<?=$this->imagePath('product')?>/<?=$product['image']?>" alt="" 
                 class="product-page-image productimage1"  title="">
        </div>

        <div  class='basketcol<?=$disabled?>  titleproduct product'>
           <?=$product['title']?>
        </div>
<?php if(!$provider_disable) {?>
        <div  class='basketcol<?=$disabled?>  deleteproduct' rel='<?=$product['id']?>' provider='<?=$provider?>' >
            <img src="/img/saychas-zero.svg" class="grayscale"   />
        </div>
<?php if($enable) {?>
        <div  class='basketcol  countproduct' id="countproduct-<?=$product['id']?>" >
            <span><div class="countproductminus <?=($product['count'] < 2)?"disabled":""?>" rel='<?=$product['id']?>' >
            </div></span><div class="countproductnum " id="countproductnum-<?=$product['id']?>" max="<?=$product['availble']?>"><?=$product['count']?>
            </div><div class="countproductplus <?=($product['count'] >= $product['availble'])?"disabled":""?>" rel='<?=$product['id']?>'></div>
            
        </div>

        <div  class='basketcol<?=$disabled?>  priceproduct' >
            <span class="price" ><tag id="priceproduct-<?=$product['id']?>"><?=number_format(((int)($product['price']*$product['count'])/100), 0, ',', '&nbsp;');?></tag>&nbsp;₽ </span>
            <?=(false and $product['oldprice'])
                ?'<span class="oldprice">'.number_format(((int)$product['oldprice']/100), 0, ',', '&nbsp;').'&nbsp;₽</span>'
                :''
            ?>
        </div>
<?php } else { ?>
        <div  class='basketcol<?=$disabled?>  priceproduct disabled' id="priceproduct-<?=$product['id']?>">
            Товара нет в наличии
        </div>
<?php }
}?>
        <div  class='basketcol<?=$disabled?>  addtofavproduct'>
            <img src="/img/saychas-zero.svg" class="favtprop" rel='<?=$product['id']?>'  />
        </div>

 </div>    

<?php endforeach;?>