<?php if ($param and count($param)) :?>
  <div class="cart-self-delivery" id="selfdeleverymainblok">
      <h2 class="h2">Самовывоз</h2>
      <h3 class="cart-self-delivery__subtitle"><b><span id="selfdeleverycountproduct">#</span> товаров из <span id="selfdeleverycountstore">#</span> магазинов</b></h3>
      <?php foreach ($param as $provider) :?>
        <div class="cart-self-delivery__store" id="seldeleveryblokrow-<?= $provider['provider_id'] ?>">
            <div class="cart-self-delivery__store-images">
                <div class="cart__store-logo"><img src="<?=$this->imagePath('provider')?>/<?= $provider['provider_logo'] ?>" alt="<?= $provider['provider_name'] ?>" title="<?= $provider['provider_name'] ?>" /></div>
                <div class="cart__store-products">
                  <?php foreach ($provider['products'] as $product): ?>
                      <?php if ($product['availble']) { ?>


                          <div class='selfdeleveryallprovider-<?= $provider['provider_id']?> selfdeleveryproduct-<?=$product['id']?>'>
                              <img title="<?= $product["title"] ?>"
                                   src="<?=$this->imagePath('product')?>/<?= (($product["image"] ) ? $product["image"] : "nophoto_1.jpeg") ?>"
                                   />
                          </div>


                          <?php }?>
                  <?php endforeach; ?>
                </div>
            </div>
            <div class="cart-self-delivery__store-info"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                </svg>
                <p><?= $provider['infostore1c'] ?></p>
            </div>
            <div class="cart-self-delivery__store-info"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                </svg>
                <p><?= $provider['provider_addressappend'] ?></p>
            </div>
        </div>
      <?php endforeach; ?>
  </div>
<?php endif; ?>
