<div class="cart-delivery">
    <h2 class="h2">Доставка</h2>
    <div class="cart-delivery__item">
        <h3 class="cart-delivery__heading">Адрес доставки:</h3>
        <div class="cart-delivery__input">
          <input id="basketuseradress" type="text"  value="<?= $basketUser['address'] ?>" name="basketuseradress" />
          <p><span class="error" id="basketuseradresserror"></span>При изменении адреса изменяется доступность товаров в корзине</p>
        </div>
    </div>
    <div class="cart-delivery__item">
        <h3 class="cart-delivery__heading">Комментарий курьерам:</h3>
        <div class="cart-delivery__input">
          <input type="text" id="basketusercomment" name="usercomment" placeholder="О чем должен знать курьер?" />
        </div>
    </div>
    <div class="cart-delivery__item">
        <h3 class="cart-delivery__heading">Получатель:</h3>
        <?php if ($legalUser) :?>
          <div class="cart-delivery__user">
              <div class="cart-delivery__user-info">
                  <div class="cart-delivery__avatar">
                      <div class="cart-delivery__avatar-letter"><?=mb_substr(trim($basketUser['name']),0,1)?></div>
                      <!--
                      <div class="cart-delivery__avatar-img"><img src="/images/testimonials/avatar1.jpg" /></div>
                      -->
                  </div>
                  <div>
                      <div class="cart-delivery__name"><?=$basketUser['name']?></div>
                      <div class="cart-delivery__phone"><?= $basketUser['phoneformated'] ?></div>
                  </div>
              </div>
                <a class="cart-delivery__logout" href="/clear-user-data">
                    <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                    </svg>
                    <span>Выйти</span>
                </a>
          </div>
        <?php else:?>
          <div class="cart-delivery__user cart-delivery__user--notlegal">
            <div class="cart__login user-modal-open">
              <span>Войти или зарегистрироваться</span>
            </div>
          </div>
        <?php endif;?>
    </div>
</div>
