<?php
if ($param and count($param)):
?>
<div class="cart__all">
  <label class="checkbox" id="checkallavailble">
    <input type="checkbox" checked="checked" />
    <span class="checkbox__check"></span>
    <span class="checkbox__value">Все товары</span>
  </label>
</div>
<div class="cart__stores">
  <?php foreach ($param as $provider): ?>
    <div class="cart__store <?=($provider['provider_disable'])?'cart__store--closed':''?>" id='providerblok-<?=$provider['provider_id']?>' rel='<?=$provider['provider_id']?>'>
      <div class="cart__store-top">
        <?php if(!$provider['provider_disable'] and $provider['availblechek']):?>
          <div class="cart__checkbox">
            <label class="checkbox" data-provider="<?=$provider['provider_id']?>" id="checkallallprovider-<?=$provider['provider_id']?>">
              <input type="checkbox" checked="checked" />
              <span class="checkbox__check"></span>
            </label>
          </div>
        <?php endif; ?>
        <div class="cart__store-logo">
          <img src="<?=$this->imagePath('provider')?>/<?=$provider['provider_logo']?>" title="<?=$provider['provider_name']?>" alt="Логотип <?=$provider['provider_name']?>" />
        </div>
        <?php if(!$provider['provider_disable']): ?>
          <div class="cart__store-info">
              <p><?=$provider['provider_worktime'].$provider["provider_timeclose"]?></p>
              <p><?=$provider['provider_address']?></p>
          </div>
        <?php else: ?>
          <div class="cart__store-notice">
              <div class="cart__store-closed"><?=$provider['provider_disable']?>
                <div class="question">?
                    <div class="question__popup"><?=$provider['infostore1c']?></div>
                </div>
              </div>
              <button class="cart__store-del">
                  <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                  </svg>
                  <span>Удалить товары</span>
              </button>
          </div>
        <?php endif; ?>
      </div>
      <ul class="cart__products">
        <?=$this->partial("/application/index/partials/basket/basket-provider-product", ["param" => $provider['products'], "provider" => $provider['provider_id'], 'provider_disable'=>$provider['provider_disable']]) ?>
      </ul>
      <?php if(!$provider['provider_disable']):?>
        <div class="cart__store-link">
          <a class="cart__store-link-plus" href="#<?=$provider['provider_id']?>"></a>
          <a href="#<?=$provider['provider_id']?>">Добавить еще товаров<span>из этого магазина бесплатно</span></a>
        </div>
        <div class="cart__store-self-delivery">
            <div>Заберу из магазина самостоятельно (-299 ₽)
              <label class="boolean" v-if="filter.type==3" rel='<?=$provider['provider_id']?>' id='selfdeleveryonoff-<?=$provider['provider_id']?>'>
                <input type="checkbox" id='selfdeleverycheckbox-<?=$provider['provider_id']?>' value='<?=$provider['provider_store_id']?>' name='selfdelevery[]' />
                <span class="boolean__check"></span>
              </label>
            </div>
            <div id="provider_addressappend<?=$provider['provider_id']?>">
              <div><?=$provider['provider_store']?></div>
              <div><?=$provider['provider_addressappend']?></div>
              <div><?=$provider['provider_worktime']?></div>
            </div>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
  </div>
<?php endif; ?>
