 <footer>
         <div class="container">
             <div class="footer">
                 <div class="footer__col">
                     <div class="footer__info">
                         <p class="footer__copyright"><?= date("Y") ?> © ООО «Сейчас»<br>
                             Все права защищены.  <?=date(DATE_ISO8601, time())?></p>
                         <div class="footer__social"><a href="#"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </a><a href="#"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </a><a href="#"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </a></div>
                     </div>
                     <div class="footer__logo"><a href="#"><img src="/img/footer-logo.png" /></a></div>
                 </div>
                 <div class="footer__col">
                     <nav class="footer__nav">
                         <div class="footer__nav-col"><a href="#">Электроника</a><a href="#">Аксессуары</a><a href="#">Одежда</a><a href="#">Детям</a><a href="#">Продукты</a></div>
                         <div class="footer__nav-col"><a href="#">Аптеки</a><a href="#">Афиша</a><a href="#">Билеты</a><a href="#">Услуги</a><a href="#">Доставка за час</a></div>
                         <div class="footer__nav-col"><a href="#">Частые вопросы</a><a href="#">Доставка</a><a href="#">Скидки</a><a href="#">Контакты</a><a href="#">Бренды</a><a href="#">Система лояльности</a><a href="#">Стать партнером</a></div>
                     </nav>
                 </div>
                 <div class="footer__col">
                     <div class="footer__right"><a class="footer__dashboard-link"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                 <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                             </svg>
                             <span>Вход для партнеров</span></a>
                         <div class="footer__icons">
                             <div class="footer__icon"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </div>
                             <div class="footer__icon"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </div>
                             <div class="footer__icon"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                     <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                                 </svg>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
  </footer>

  <?= (!$this->legalUser) ? $this->partial("/application/common/user-modal-win", ["param" => []]) : "" ?>
  <?= $this->partial("/application/common/service-modal-window", ["param" => []]) ?>
