         <footer id="footer" class="blokc">

                <div class="iblokl contentwrapper">
                    <div class="fitem fcopy">
                        <div class="emptyblock"></div> <div class="emptyblock"></div>
                        <p style="padding-top:30px;">2021&copy; ООО &laquo;Сейчас&raquo; <br>все права защищены</p>
                        <?= date("Y-m-d H:i:s") ?>
                    </div>
                    <div class="fitem flogo"><span class="flogospan"></span></div>
                    <div class="fitem fcontent" >
                        <div class="pw-contentblock cblock-4">
                            <div class="contentpadding footerlink">
                                <a href="/catalog/000000002" class="blok" >Электроника</a>
                                <a href="#" class="blok" >Аксессуары</a>
                                <a href="#" class="blok" >Одежда</a>
                                <a href="#" class="blok" >Детям</a>
                                <a href="#" class="blok" >Продукты</a>
                            </div>
                        </div>
                        <div class="pw-contentblock cblock-4">
                            <div class="contentpadding footerlink">
                                <a href="#" class="blok" >Аптеки</a>
                                <a href="#" class="blok" >Афиша</a>
                                <a href="#" class="blok" >Билеты</a>
                                <a href="#" class="blok" >Услуги</a>
                                <a href="#" class="blok activlink" >Доставим за час</a>
                            </div>
                        </div>
                        <div class="pw-contentblock cblock-4">
                            <div class="contentpadding footerlink">
                                <a href="#" class="blok" >Частые вопросы</a>
                                <a href="#" class="blok" >Доставка</a>
                                <a href="#" class="blok" >Скидки</a>
                                <a href="#" class="blok" >Контакты</a>
                                <a href="#" class="blok" >Бренды</a>
                                <a href="#" class="blok" >Система лояльности</a>
                                <a href="#" class="blok" >Стать партнером</a>
                            </div>
                        </div>
                        <div class="pw-contentblock cblock-4">
                            <div class="contentpadding footerlink">
                                <span  class="parthnerenter blokr" ><b class="brandcolor">:</b><a href="#">Вход для партеров</a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>