<footer class="footer">
        <div class="container">
            <div class="footer__logo"><img src="/img/footer-logo.png" />
                <div class="footer__copyright">2021 © ООО «Сейчас»<br>Все права защищены.</div>
            </div>
            <nav class="footer__nav">
                <div><a href="#">Электроника</a><a href="#">Аксессуары</a><a href="#">Одежда</a><a href="#">Детям</a><a href="#">Продукты</a></div>
                <div><a href="#">Аптеки</a><a href="#">Афиша</a><a href="#">Билеты</a><a href="#">Услуги</a><a class="accent-color" href="#">Доставим за час</a></div>
                <div><a href="#">Частые вопросы</a><a href="#">Доставка</a><a href="#">Скидки</a><a href="#">Контакты</a><a href="#">Бренды</a><a href="#">Система лояльности</a><a href="#">Стать партнером</a></div>
            </nav>
            <div class="footer__contact">
                <div class="footer__phone">+7 (495) 445-04-55</div>
                <div class="footer__email"><a href="mailto:info@saychas.ru">info@saychas.ru </a><span>для общих вопросов и сотрудничества</span></div>
                <div class="footer__email"><a href="mailto:sales@saychas.ru">sales@saychas.ru</a><span>для вопросов и сотрудничества с поставщиками</span></div>
            </div>
            <div class="footer__right"><a class="icon-link" href="/control-panel">
                    <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    width="17px" height="15px">
                    <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                    d="M10.693,6.769 L7.84,3.189 C6.86,2.181 4.590,3.692 5.588,4.700 L6.806,5.925 C7.83,6.204 6.991,6.431 6.600,6.431 L1.750,6.431 C1.171,6.431 0.695,6.909 0.695,7.499 C0.695,8.88 1.167,8.567 1.750,8.567 L6.600,8.567 C6.989,8.567 7.83,8.794 6.806,9.73 L5.588,10.299 C4.590,11.306 6.86,12.817 7.84,11.810 L10.688,8.266 C11.109,7.852 11.110,7.183 10.693,6.769 ZM14.534,2.142 L12.420,2.142 C11.835,2.142 11.361,1.662 11.361,1.71 C11.361,0.479 11.835,0.0 12.420,0.0 L15.594,0.0 C16.374,0.0 17.3,0.643 17.3,1.428 L17.3,13.571 C17.3,14.359 16.370,14.999 15.594,14.999 L12.420,14.999 C11.835,14.999 11.361,14.520 11.361,13.928 C11.361,13.336 11.835,12.856 12.420,12.856 L14.534,12.856 C14.733,12.856 14.888,12.697 14.888,12.500 L14.888,2.499 C14.888,2.302 14.729,2.142 14.534,2.142 Z"/>
                    </svg>
                    <span>Вход для партнеров</span></a>
                <div class="footer__icons" style="opacity: 0;"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                    </svg>
                    <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                    </svg>
                </div>
            </div>
        </div>
</footer>

<?= (!$this->legalUser) ? $this->partial("/application/common/user-modal-win", ["param" => []]) : "" ?>
<?= $this->partial("/application/common/service-modal-window", ["param" => []]) ?>
