<div id="headermenu" >
    <div class="headermenucontent">
        <a  href="<?= $this->url('home') ?>">Home</a>
        <a  href="/catalog/000000006"  >Каталог</a>
        <a  href="/product/000000000014" >Товар</a>
        <a  href="/user" >User</a>
        <a  href="/phpmyadmin" >Sql</a>
        <a  href="/preview" >Help</a>
        <span  class="parthnerenter" ><b class="brandcolor">:</b><a href="/control-panel" target="_blank">Вход для партеров</a></span>
    </div>
</div>