<div class="header__top">
   <div class="container">
      <nav class="header__nav">
        <div class="header__nav-items">
            <a href="<?= $this->url('home') ?>">Home</a>
            <a href="/catalog/000000006"  >Каталог</a>
            <a href="/product/000000000014" >Товар</a>
            <a href="/user" >User</a>
            <a href="/phpmyadmin" >Sql</a>
            <a href="/preview" >Help</a>
        </div>
        <div class="header__nav-dashboard">
            <a href="/control-panel" target="_blank">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                   <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                </svg>
                <span>Вход для партнёров</span>
            </a>
        </div>
      </nav>
   </div>
</div>