<?php
use Application\Resource\Resource;
?>
<div class="header__profile">
  <a <?= ($addressLegal) ? 'href="/basket"' : ''?> >
     <div class="header__icon">
        <img src="/img/icons/icon-cart.svg" />
        <div class="header__cart-count" id="zakazcount" style="display: none;"><?=$count?></div>
     </div>
     <span><?= Resource::THE_BASKET ?></span>
  </a>
  <?php if (!$addressLegal):?>
    <div class="header__profile-popup header__profile-popup--auth header__profile-popup--basket">
        <a class="open-user-address-form">
          <b>Сначала введите адрес доставки</b>
        </a>
    </div>
  <?php endif; ?>
</div>
