<?php
use Application\Resource\Resource; 
?>

<div class="header__profile">
    <a>
       <div class="header__icon">
            <svg width="58" height="58" viewBox="0 0 58 58" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M28.999 0.999023C44.463 0.999023 56.999 13.535 56.999 28.999C56.999 44.463 44.463 56.999 28.999 56.999C13.535 56.999 0.998993 44.463 0.998993 28.999C0.998993 13.535 13.535 0.999023 28.999 0.999023Z" fill="white" stroke="#FF4B2D" stroke-width="2" />
            </svg>
       </div>
       <span><?= Resource::USER_MENU_PROFILE ?></span>
       <div class="header__icon-popup">
       </div>
    </a>
    <?php if ($userLegal) : ?>
        <!-- profile links-->
       <div class="header__profile-popup header__profile-popup--links">
            <a href="#">
                <b><?= $username ?></b>
            </a>
            <a href="/user"><?= Resource::USER_MENU_PROFILE_PAGE ?></a>
            <a href="/client-orders"><?= Resource::USER_MENU_ORDERS ?></a>
            <a href="#"><?= Resource::USER_MENU_POST ?></a>
            <a href="/clear-user-data">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                   <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                </svg>
                <span><?= Resource::USER_MENU_EXIT ?></span>
            </a>
        </div>
    <?php else : ?>
        <!-- auth popup-->
        <div class="header__profile-popup header__profile-popup--auth">
            <a class="user-modal-open">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                   <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                </svg>
                <b><?= Resource::MESSAGE_ENTER_OR_REGISTER_TITLE ?></b>
            </a>
        </div>
    <?php endif; ?>
</div>
