<form method='POST'>
        <div class='blok' ><input type='phone' name='userPhone' class="phoneInput"/></div>
        <div class='blok' ><input type=button  value='Войти' id='userAuthBotton'></div>
        <div id='userAuthError' ></div>
</form>

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

