<li>имя: <?=$user->getName()?></li>
<li>телефон: <?=$user->getPhone()?></li>
<?php
   ///$content.="<li>пароль: {$user->getPassword()}</li>";
        if(count($userData)){//$uesrId = $user->getId();
            $content.="<ol>Адреса:"; 
            foreach($userData as $ud) {
                $content.="<li><strong>{$ud->getAddress()}</strong><span class='blok mini gray'>{$ud->receiveTimestamp()}</span>";
                //$content.="<span class='blok mini'>{$ud->getTimestamp()}</span>";
                $content.="</li>";
            }
            $content.="</ol>"; 
        }
   echo $content;   