<!--<style>
body {
  margin: 0;
  padding: 0;
  background-color: #17a2b8;
  height: 100vh;
}
#login .container #login-row #login-column #login-box {
  margin-top: 120px;
  max-width: 600px;
  height: 320px;
  border: 1px solid #9C9C9C;
  background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
  padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
  margin-top: -85px;
}
</style>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="text" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="#" class="text-info">Register here</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>-->

<div class="container">
    <div class="row justify-content-center align-items-center" style="height:100vh">
        <div class="col-4">
            <div class="card">
                <div class="card-header">Чтоб залогиниться просто нажать на Ввод. Если изменить пароль или логин, то залогиниться не удастся.</div>
                <div class="card-body">
                    <form method="POST" action="<?= $action ?>" autocomplete="off">
                        <input type="hidden" name="returnUrl" value="<?= $returnUrl ?>" />
                        <div class="input-group mb-2 input-group-sm">
                            <div class="input-group-prepend">
                                <span  class="field-prefix input-group-text">Username</span>
                            </div>
                            <input type="text" placeholder="username" class="form-control" name="username" value='banzaii'>
                        </div>
                        <div class="input-group mb-2 input-group-sm">
                            <div class="input-group-prepend">
                                <span  class="field-prefix input-group-text">Password</span>
                            </div>
                            <input type="password" placeholder="****" class="form-control" value="vonzaii" name="password">
                        </div>
<!--                        <button type="button" id="sendlogin" class="btn btn-primary">login</button>-->
                        <input type="submit" id="sendlogin" class="btn btn-primary" value="Ввод" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>