<?php
//$this->headTitle($this->title, 'PREPEND');
//$this->headTitle(, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?><div class="container mainconteiner"  >
    <div  class="contentwrapper">
        <?= $this->bread ?> 

        <h2><?= $this->title ?></h2> 
        <div id="user-basket">
            <form method='POST' id='user-basket-form'>   
                <div class="pw-contentblock cblock-5">
                    <div class='nopub ' id='checkallavailble' >Выбрать все</div>
         <?=$this->partial("/application/index/partials/basket/basket-provider", ["param" => $this->content])?>
                </div>
                <div class="pw-contentblock cblock-3">
                    <div class="contentpadding">
                        <!-- div class='blok pwbox'> сервисный блок</div -->
        <?=$this->partial("/application/index/partials/basket/basket-payinfo")?>               
                    </div>
                </div>  
            </form>
        </div>
    </div>
