<?php
    $this->headTitle($this->title, 'PREPEND');
    $this->inlineScript()->prependFile($this->basePath('/js/basket.js'));
?>
<div class="container mainconteiner"  >
    <div  class="contentwrapper">
        <?= $this->bread ?> 

        <h2><?= $this->title ?></h2> 
        <div id="user-basket">
            <form method='POST' id='user-basket-form'>   
                <div class="pw-contentblock cblock-5">
                    <?php //exit(print_r($this->content)); ?>
                    <?= $this->partial("/application/index/partials/basket/basket-provider", ["param" => $this->content]) ?>
                    
                    <?= $this->partial("/application/index/partials/basket/basket-user", ["basketUser" => $this->basketUser]) ?>                     
                    <div class='pw-contentblock cblock-1' id='basketordermerge'></div>            
                    <?php /* $this->partial("/application/common/basket-order-merge") */ ?>      
                    <?= $this->partial("/application/index/partials/basket/basket-self-delevery") ?>      
                    <?= $this->partial("/application/index/partials/basket/basket-pay-card", ['cardinfo' => $this->cardinfo]) ?>    
                    
                </div>
                <div class="pw-contentblock cblock-3">
                    <div class="contentpadding">
                        <!-- div class='blok pwbox'> сервисный блок</div -->
                        <?= $this->partial("/application/index/partials/basket/basket-paysection") ?>      
                    </div>
                </div>  
        </form>
    </div>
</div>
