<?php
//$this->headTitle(Application\Resource\Resource::THE_BRANDS, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/brands.js'));
?><section class="catalog">
  <div class="page-heading">
      <h1 class="h1"><?= $this->title ?></h1>
      <?= $this->partial("/application/common/range-filter-select", ['data' => $this->data])?>
<?php /*      <select class="select catalog__sort">
          <option selected="selected" value="">Сначала свежие</option>
          <option value="">Сначала популярные</option>
          <option value="">Сначала дешевые</option>
          <option value="">Сначала дорогие</option>
      </select>
 * 
 */?>
  </div>
  <div class="catalog__wrap" id="catalog-wrap">
    <aside class="catalog__sidebar">
        
      <?= $this->partial("/application/index/partials/brand/bread-crumbs-menu", [ "url" => "brand", "breadCrumbs" => $this->breadCrumbs, "id" => $this->id, "category_id" => $this->category_id]) ?>
    </aside>
    <div class="catalog__content">
        <pre id="brandcontent"></pre>
    </div>
  </div>
</section>