<?php
$this->headTitle(Application\Resource\Resource::THE_CATALOG_OF_PRODUCTS, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/catalog.js'));
?>
<section class="catalog">
  <div class="page-heading">
      <h1 class="h1"><?= $this->title ?> <span>312 515 товаров</span></h1>
      <select class="select catalog__sort">
          <option selected="selected" value="">Сначала свежие</option>
          <option value="">Сначала популярные</option>
          <option value="">Сначала дешевые</option>
          <option value="">Сначала дорогие</option>
      </select>
  </div>
  <div class="catalog__wrap" id="catalog-wrap">
    <aside class="catalog__sidebar">
      <?= $this->partial("/application/index/partials/catalog/bread-crumbs-menu", ["breadCrumbs" => $this->breadCrumbs, "id" => $this->id]) ?>
      <?= $this->partial("/application/index/partials/catalog/filters", ["filters" => $this->filterform, "id" => $this->id]) ?>
    </aside>
    <div class="catalog__content">
      <section class="section">
        <div class="products-grid products-grid--3">
          <div v-for="(product, name) in products" :key="name" class="product">
              <div class="product__label">Акция</div>
              <a class="product__img" :href="'/product/' + name">
                <img :src="'/images/product/' + product.image" />
              </a>
              <a class="product__title" href="#">{{ product.title }}</a>
              <div class="product__reviews">
                  <div class="product__reviews-grade">
                      <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                      </svg>
                      <span>4.7</span>
                  </div>
                  <a class="product__reviews-link" href="#">28 отзывов</a>
              </div>
              <div class="product__price">
                  <div class="product__price-current">{{ (product.price / 100).toLocaleString() }} ₽</div>
                  <div class="product__price-old">21 990 ₽</div>
              </div>
              <div class="product__tocart">
                <button class="btn btn--primary paybutton" :rel="name">В корзину</button>
              </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>
