<?php
$this->headTitle('Каталог товаров', 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/catalog.js'));
?><div class="container"  style="position:relative; max-width:1600px; min-height:calc(100vh - 160px) " >
    <div id="left-col">
        <div class="content-col">
            <form method="post" id="filtrform">
                <input type='hidden' name='category_id' value='<?= $this->id ?>'>
                <div id="filtrblock" class="container">
                    <?= $this->breadmenu ?>
                    <?= $this->filterform ?><br class="both"/>
                </div>
            </form>
        </div>
    </div>
    <div id="main-col">
        <?= $this->bread ?>
        <div class="content-col" style="" id="tovary">
            <div id='ajaxfiltranswer'></div>
            <br class="both">
            <h1><?= $this->title ?>  <?= ($this->id) ? "<span>id: " . $this->id . "</span>" : "" ?></h1>
            <div id="tovar-list"></div>
        </div>
    </div>
</div>
