<?php
use Application\Resource\Resource;
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/client-orders.js'));
?>
<div class="page-heading">
    <h1 class="h1">История заказов</h1>
</div>
<div class="profile-page">
  <?= $this->partial("/application/index/partials/user/user-menu", ["auth" => $this->auth]) ?>
  <div id="client-orders">
    <div v-if="preparedOrders.length" class="orders-history">
        <div v-for="order in preparedOrders" class="orders-history__item">

          
        </div>
    </div>
  </div>
</div>
<pre id="order-list" style="display: none;">
</pre>
