<?php
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/client-orders.js'));
?>
<div class="page-heading">
    <h1 class="h1">Мой профиль</h1>
</div>
<div class="profile-page">
  <?= $this->partial("/application/index/partials/user/user-menu", ["auth" => $this->auth]) ?>
  <div class="orders-history" id="client-orders">
      <div v-for="order in orders" class="orders-history__item">
        <div class="orders-history__left">
          <div v-if="order.deliveryInfo.delivery.length" class="orders-history__delivery">
              <h2>Доставка</h2>
              <div class="orders-history__statuses">
                  <div class="orders-history__status orders-history__status--progress"><span>Собирается</span></div>
                  <div class="orders-history__status orders-history__status--ready">Готов</div>
                  <div class="orders-history__status orders-history__status--deliveried">Доставлен</div>
                  <div class="orders-history__status orders-history__status--canceled">Отменен</div>
              </div>
              <div class="orders-history__text">
                  <p>{{order.deliveryInfo.delivery.length}} доставок, сегодня с 15 до 16</p>
                  <p>{{order.basketInfo.userGeoLocation.value}}</p>
              </div>
              <div class="orders-history__products">
                  <a href="">
                      <div class="product-small-img">
                        <img src="/images/products/product1.jpg" />
                      </div>
                  </a>
              </div>
          </div>
        </div>
        <div class="orders-history__right">
          <div class="panel panel--cart panel--history">
              <input class="orders-history__detailed-trigger" type="checkbox" id="orders-detailed" />
              <div class="panel__delivery">
                  <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                      </svg>
                      <div>
                          <h2>Заказ №{{order.orderId}}</h2>
                          <p>Создан {{order.date}}</p>
                      </div>
                  </div>
              </div>
              <div class="panel__zip"></div>
              <div class="panel__price">
                  <div class="panel__price-current">17 990 ₽</div>
                  <div class="panel__price-old">21 990 ₽</div>
              </div>
              <div class="panel__bonuses"><span>+179</span> сейбонов<div class="question">
                      <div class="question__icon">?</div>
                  </div>
              </div>
              <div class="panel__table">
                  <div class="panel__tr">
                      <div>Товары (13)</div>
                      <div class="panel__tr-items-total">
                          <div>389 800 ₽</div>
                          <div>402 190 ₽</div>
                      </div>
                  </div>
                  <div v-if="order.delieveries.length" class="panel__tr">
                      <div> <b>Доставка</b></div>
                      <div>{{ order.delievery_price.toLocaleString() }} ₽</div>
                  </div>
                  <div v-if="order.pickup.length" class="panel__tr">
                      <div>Самовывоз</div>
                      <div>0 ₽</div>
                  </div>
              </div>
              <label class="btn btn--secondary" for="orders-detailed">Подробности заказа</label>
          </div>
        </div>
      </div>
  </div>
</div>
<div id="order-list">
</div>
