<?php
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/client-order-page.js'));
?>
<div class="profile-order">
    <div class="page-heading">
        <h1 class="h1"><a class="page-heading__back" href="/user/orders"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16px" height="13px">
                    <path fill-rule="evenodd" fill="currentColor" d="M4.499,4.999 L14.499,4.999 C15.328,4.999 15.999,5.671 15.999,6.499 C15.999,7.328 15.328,7.999 14.499,7.999 L4.499,7.999 C3.671,7.999 2.999,7.328 2.999,6.499 C2.999,5.671 3.671,4.999 4.499,4.999 Z" />
                    <path fill-rule="evenodd" fill="currentColor" d="M0.903,4.974 L4.974,0.903 C5.560,0.317 6.510,0.317 7.96,0.903 C7.681,1.489 7.681,2.439 7.96,3.25 L3.24,7.96 C2.439,7.681 1.489,7.681 0.903,7.96 C0.317,6.510 0.317,5.560 0.903,4.974 Z" />
                    <path fill-rule="evenodd" fill="currentColor" d="M7.96,9.974 L3.24,5.903 C2.439,5.317 1.489,5.317 0.903,5.903 C0.317,6.489 0.317,7.439 0.903,8.25 L4.974,12.96 C5.560,12.681 6.510,12.681 7.96,12.96 C7.681,11.510 7.681,10.560 7.96,9.974 Z" />
                </svg>
            </a><span><?=$this->title?></span></h1>
    </div>
    <div class="profile-order__wrap">
        <div class="profile-order__requisitions">
            <div class="profile-order__requisition">
                <div class="profile-order__requisition-head"><span>Доставка из</span>
                    <div class="profile-order__requisition-logo"><img src="/images/stores/store1.jpg" /></div>
                    <div class="orders-history__statuses">
                        <div class="orders-history__status orders-history__status--progress"><span>Собирается</span></div>
                        <div class="orders-history__status orders-history__status--ready">Готов</div>
                        <div class="orders-history__status orders-history__status--deliveried">Доставлен</div>
                        <div class="orders-history__status orders-history__status--canceled">Отменен</div>
                    </div>
                </div>
                <div class="profile-order__requisition-items">
                    <div class="product-tr">
                        <div class="product-tr__img product-small-image"><img src="/images/products/product1.jpg" /></div>
                        <div class="product-tr__title">Смартфон Huawei P Smart 2021 4+128GB Crush Green</div>
                        <div class="product-tr__quantity">1 шт</div>
                        <div class="product-tr__price">
                            <div class="product-tr__price-actual">17 990 ₽</div>
                            <div class="product-tr__price-old">21 990 ₽</div>
                        </div>
                        <div class="product-tr__wishlist"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                            </svg>
                        </div>
                    </div>
                    <div class="product-tr">
                        <div class="product-tr__img product-small-image"><img src="/images/products/product1.jpg" /></div>
                        <div class="product-tr__title">Смартфон Huawei P Smart 2021 4+128GB Crush Green</div>
                        <div class="product-tr__quantity">12 шт<span class="product-tr__quantity-new">10 шт</span></div>
                        <div class="product-tr__price">
                            <div class="product-tr__price-actual">21 990 ₽</div>
                        </div>
                        <div class="product-tr__wishlist"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="profile-order__info">
            <div class="panel panel--cart panel--history"><input class="orders-history__detailed-trigger" type="checkbox" checked="checked" id="orders-detailed" />
                <div class="panel__delivery">
                    <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                        </svg>
                        <div>
                            <h2>Заказ №000234</h2>
                            <p>Создан 12 мая 2021 в 14:46</p>
                        </div>
                    </div>
                    <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                        </svg>
                        <div>
                            <h2>5 доставок</h2>
                            <p>Сегодня с 15 до 16</p>
                            <p>Москва, Самая длинная угрешская улица, 2с34</p>
                        </div>
                    </div>
                    <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                        </svg>
                        <div>
                            <h2>2 самовывоза</h2>
                        </div>
                    </div>
                    <div class="panel__delivery-item"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.999 0.999023C13.418 0.999023 16.999 4.58102 16.999 8.99902C16.999 13.418 13.418 16.999 8.999 16.999C4.581 16.999 0.999001 13.418 0.999001 8.99902C0.999001 4.58102 4.581 0.999023 8.999 0.999023Z" stroke="currentColor" stroke-width="2" />
                        </svg>
                        <div>
                            <h2>Оплачен</h2>
                            <p>Картой 5213 2487 **** 0817</p>
                        </div>
                    </div>
                </div>
                <div class="panel__zip"></div>
                <div class="panel__price">
                    <div class="panel__price-current">394 990 ₽</div>
                    <div class="panel__price-old">403 990 ₽</div>
                </div>
                <div class="panel__bonuses"><span>+179</span> сейбонов<div class="question">
                        <div class="question__icon">?</div>
                    </div>
                </div>
                <div class="panel__table">
                    <div class="panel__tr">
                        <div>Товары (13)</div>
                        <div class="panel__tr-items-total">
                            <div>389 800 ₽</div>
                            <div>402 190 ₽</div>
                        </div>
                    </div>
                    <div class="panel__tr">
                        <div> <b>Доставка за час</b></div>
                        <div>899 ₽</div>
                    </div>
                    <div class="panel__tr">
                        <div>Самовывоз</div>
                        <div>0 ₽</div>
                    </div>
                </div><button class="btn btn--secondary">Отменить заказ</button>
                <div class="panel__notice">Вы можете отменить заказ, пока он ещё не собран. Если возникли проблемы с заказом — просто позвоните нам +7 (495) 445-04-55</div>
            </div>
        </div>
    </div>
</div>
<script>
   var userOrder = <?=json_encode($this->orderInfo)?>;
</script>
<pre>
  <?= print_r($this->orderInfo); ?>
</pre>
<h3>Из аякса</h3>
<div id="client-order"></div>
