<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->inlineScript()->prependFile($this->basePath('/js/homepage.js'));
?>

<section>
    <div class="homeslider">
        <div class="homeslider__slide"><img src="/images/homeslider/slide1.jpg" /></div>
        <div class="homeslider__slide"><img src="/images/homeslider/slide1.jpg" /></div>
        <div class="homeslider__slide"><img src="/images/homeslider/slide1.jpg" /></div>
        <div class="homeslider__slide"><img src="/images/homeslider/slide1.jpg" /></div>
        <div class="homeslider__slide"><img src="/images/homeslider/slide1.jpg" /></div>
    </div>
</section>
<div id="sale-products">
<section class="section" v-if="length > 0">
    <h2 class="h2 section__heading">Горящие предложения</h2>
    <div class="products-carousel">
      <?= $this->partial("/application/common/product") ?>
    </div>
</section>
</div>
<div id="popular-products">
<section class="section" v-if="length > 0">
    <h2 class="h2 section__heading">Популярные товары в этом месяце</h2>
    <div class="products-grid">
      <?= $this->partial("/application/common/product") ?>
    </div>
</section>
</div>
<section class="section" style="display: none;">
    <div class="banners-carousel"><a href="#"><img src="/images/banners/banner1.jpg" /></a><a href="#"><img src="/images/banners/banner1.jpg" /></a><a href="#"><img src="/images/banners/banner1.jpg" /></a><a href="#"><img src="/images/banners/banner1.jpg" /></a></div>
</section>
<div id="popular-brands" style="display: none2;">
  <section class="section" v-if="length > 0">
      <h2 class="h2 section__heading">Популярные бренды</h2>
      <div class="brands-grid">
        <a v-for="brand in brands" class="brands-grid__logo" :href="'/brand/'+brand.url" :alt="brand.title">
          <img :src="'/images/brand/'+brand.image" />
        </a>
      </div>
  </section>
</div>
<div id="viewed-products">
  <section class="section" v-if="length > 0">
      <h2 class="h2 section__heading">Вы смотрели</h2>
      <div class="products-carousel">
        <?= $this->partial("/application/common/product") ?>
      </div>
  </section>
</div>
