<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* echo '<br/>';
  echo $this->menu; */
?>
 <div class="container">



  </div>

<div class="container" >	
    <div class="card-deck"> 
        <div class="card">
            <h2 class="card-header">типы характеристик (characteristic_type)</h2>
            <div class="card-body">
                <div class="container" >
                    <ul>
                        <li>0 - Заголовок</li>
                        <li>1 - Строка </li>
                        <li>2 - Число </li>
                        <li>3 - Булево </li>
                        <li>4 - СправочникСсылка.ДопХарактеристикиНоменклатуры</li>
                        <li>5 - СправочникСсылка.Поставщики</li>
                        <li>6 - СправочникСсылка.Бренды</li>
                        <li>7 - СправочникСсылка.Цвета</li>
                        <li>8 - СправочникСсылка.Страна</li>
                    </ul>
                </div>
            </div>   
        </div>
        <div class="card">
            <h2 class="card-header">User Data Form</h2>
            <div class="card-body">
                <div class="container" >
                    <div id="image_div"></div>
                    <input type="text" placeholder="Input some data" id="inputSomeDataId" value="000000004"/>
                    <input type="button" id="userDataFormId" class="btn btn-primary" value="Send SMS"/>
                    <input type="button" id="codeFeedbackId" class="btn btn-primary" value="Send back"/> 
                    <input type="button" id="getClientInfoId" class="btn btn-primary" value="Get Client Info"/>
                    <input type="button" id="setClientInfoId" class="btn btn-primary" value="Set Client Info"/>
                    <input type="button" id="updateClientInfoId" class="btn btn-primary" value="Update Client Info"/>
                    <input type="button" id="changeClientPasswordId" class="btn btn-primary" value="Change Client Password"/>
                    <input type="button" id="getImageFromFtpId" class="btn btn-primary" value="Get Image From Ftp"/>
                    <input type="button" id="clientLogin" class="btn btn-primary" value="Client Login"/>
                    <input type="button" id="sendTinkoff" class="btn btn-primary" value="Tinkoff callback"/>
                    <input type="button" id="sendAveragePrice" class="btn btn-primary" value="setAveragePrice callback"/>
                    
                    
                    
                </div>
            </div>   
        </div>
    </div>
</div>

<div class="container">	
    <div class="card-deck"> 
        <div class="card">
            <h2 class="card-header">Запрос магазинов по адресу</h2>
            <div class="card-body">
                <div class="container" >
                    <input id="address" name="suggestions"  placeholder="укажи адрес доставки"/>
                    <div id="adesserror" class="errorblock none"></div>
                    <div id="dadataanswer" style="font-size:12px; "></div>
                    <div id="dadataask" style="font-size:12px; color:#ccc"></div>                 
                </div>  
            </div>
        </div> 
        <div class="card" id="ycard" style="display:none;">
            <!-- div style='min-heignt:300px;' -->
            <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&mode=debug" type="text/javascript"></script>
            <script type="text/javascript">
                ymaps.ready(init);
                function init() {
                    myMap = new ymaps.Map("map", {
                        center: [55.71, 37.68],
                        zoom: 7
                    });
                }
            </script>   

            <div class="card-body" id="map">
                <!-- 'geo_lat' => "55.7132713"  'geo_lon' => "37.6860004" -->
                <div id="geocoords"></div>
            </div>
            <!-- /div --> 
        </div> 
    </div>        
    <p><hr/></p>
<div class="card-deck">        

    


</div>
<div class="card-deck"> 	

    <div class="card">
        <h2 class="card-header">Телефон</h2>
        <div class="card-body">  
            <div class="container">
                <p><input name=phonesend  val=""  id="phonesend" class="phoneInput" placeholder="+7-999-999-9999" style="margin:5px 0;padding:4px" ></p>

            </div>  
        </div> 
    </div> 


</div>
<div class="card-deck"> 	

    <div class="card">
        <h2 class="card-header">Рейтинг товара</h2>
        <div class="card-body">  
            <form id="productRatingForm" >
                
                <p><input   name='productId' val=""  id="productId"  placeholder="id продукта" value="000000000017" required ></p>
                <p>
                    <select   name='rating'  id="productRating" >
                        <option value="0" >&#9733;</option>
                        <option value="4" >&#9733;&#9733;&#9733;&#9733;&#9733;</option>
                        <option value="3" >&#9733;&#9733;&#9733;&#9733;</option>
                        <option value="2" >&#9733;&#9733;&#9733;</option>
                        <option value="1" >&#9733;&#9733;</option>
                       
                    </select>
                    <select   name='page'  id="reviewPaging" >
                         <option value="0" >Page 0</option>
                        <option value="1" >Page 1</option>
                        <option value="2" >Page 2</option>
                        <option value="3" >Page 3</option>
                        
                    </select>
                     <select   name='sort'  id="reviewSortOrder" >
                        <option value="0" >Сначала свежие</option>
                        <option value="1" selected >Сначала хорошие</option> 
                        <option value="2" >Сначала отрицательные</option>
                         
                        
                        
                        
                    </select>
                    
                </p>
                <button id='productRatingButton' >Отправить рейтинг</button>
                <button id='productReview' >Получить отзывы</button>
                
                <pre id="productRatingAnswer"></pre>
                

            </form>  
        </div> 
    </div> 
    <div class="card">
        <h2 class="card-header">Оставить отзыв</h2>
        <div class="card-body">  
            <form id="productReviewForm" <?php /*enctype='multipart/form-data'*/?> >
                
                <p><input   name='productId' val=""  id="productReviewId"  placeholder="id продукта" value="000000000017" required ></p>
                <p>
                    <select   name='rating'  id="productRatingReview" >
                        <option value="4" >&#9733;&#9733;&#9733;&#9733;&#9733;</option>
                        <option value="3" >&#9733;&#9733;&#9733;&#9733;</option>
                        <option value="2" >&#9733;&#9733;&#9733;</option>
                        <option value="1" >&#9733;&#9733;</option>
                        <option value="0" >&#9733;</option>
                    </select>
                </p>
                <p>
                    <textarea name="reviewMessage" id="reviewMessage" placeholder="отзыв о товаре"></textarea>
                </p>
                <input type="file" id="file" multiple="true" name="file" >
                
                <button id='productReiewButton' >Отправить отзыв</button>
                
                
                <pre id="productReviewAnswer"></pre>
                

            </form>  
        </div> 
    </div> 


</div>
</div>    
