<?php

use Application\Resource\Resource;

//$this->headTitle(Resource::THE_CATALOG_OF_PRODUCTS, 'PREPEND');
$this->headTitle($this->category, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?>
<section class="product-card">
    <?= $this->partial("/application/index/partials/product-page/bead-crumbs", ["breadCrumbs" => $this->breadCrumbs, "id" => $this->id]) ?>
    <div class="product-card__heading">
       <h1><?= $this->title ?> <?php if (false and $this->id) echo "<span>id: " . $this->id . "</span>"; ?></h1>
    </div>
    <div class="product-card__top">
        <?= $this->partial("/application/index/partials/product-page/grade") ?>
        <div class="product-card__code">Код товара: <?= $this->id ?><?php // = $this->append['vendorCode'] ?></div>
    </div>
    <div class="product-card__main">
        <?= $this->partial("/application/index/partials/product-page/product-images", ["images" => $this->images, "image_path" => $this->imagePath('product')]) ?>
        <div class="product-card__info">
            <?= $this->partial("/application/index/partials/product-page/options") ?>
            <?= $this->partial("/application/index/partials/product-page/main-characteristics", ["characteristics" => $this->characteristics]) ?>
        </div>
        <?=($this->price) ? $this->partial("/application/index/partials/product-page/pay-section",
                [
                   "price" => $this->price,
                   "oldPrice" => $this->oldPrice,
                   "discont" => $this->discont,
                   "price_formated" => $this->price_formated,
                   "id" => $this->id,
                   "brand" => $this->brand,
                   "provider" => $this->provider,
                   "image_path_brand" => $this->imagePath('brand'),
                    "image_path_provider" => $this->imagePath('provider'),
                    "isFav" => $this->isFav,
                ]) : ""
        ?>
        <?= $this->partial("/application/index/partials/product-page/description", ["description" => $this->description, "id" => $this->id]) ?>
        <?= $this->partial("/application/index/partials/product-page/characteristics", ["characteristics" => $this->characteristics]) ?>
        <?= $this->partial("/application/index/partials/product-page/append-info", ["params" => $this->append]) ?>
        <div class="recommendations" style="display: none;">
            <h2 class="product-card__section-heading">Рекомендуем присмотреться </h2>
            <div class="products-carousel products-carousel--4 recommendations__carousel">
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
                <div class="product product--recommendation">
                    <div class="product__label">Акция</div><a class="product__img" href="#"><img src="/images/products/product1.jpg" /></a><a class="product__title" href="#">Смартфон Huawei P Smart 2021 4+128GB Crush Green</a>
                    <div class="product__reviews">
                        <div class="product__reviews-grade">
                            <svg
                            xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            width="17px" height="17px">
                            <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                            d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                            </svg>
                            <span>4.7</span>
                        </div><a class="product__reviews-link" href="#">28 отзывов</a>
                    </div>
                    <div class="product__price">
                        <div class="product__price-current">17 990 ₽</div>
                        <div class="product__price-old">21 990 ₽</div>
                    </div>
                    <div class="product__tocart"><button class="btn btn--primary">В корзину</button>
                        <ul class="product__attributes">
                            <li><span>Диагональ экрана, дюймы</span> 1.4</li>
                            <li><span>Разрешение экрана</span> 360x360</li>
                            <li><span>Беспроводные интерфейсы</span> NFC</li>
                            <li><span>Совместимость</span> Android</li>
                            <li><span>Защита от влаги</span> Да</li>
                        </ul>
                    </div>
                </div>
            </div>
            <ul class="recommendations__table">
                <li><span>Диагональ экрана, дюймы</span></li>
                <li><span>Разрешение экрана</span></li>
                <li><span>Беспроводные интерфейсы</span></li>
                <li><span>Совместимость</span></li>
                <li><span>Защита от влаги</span></li>
            </ul>
        </div>
        <div class="testimonials" style="display: none">
            <h2 class="product-card__section-heading">Отзывы о товаре </h2>
            <div class="testimonials__photos testimonials__photos--carousel">
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
            </div>
            <div class="testimonials__sort"><select class="select">
                    <option selected="selected" value="">Сначала свежие</option>
                    <option value="">Сначала популярные</option>
                    <option value="">Сначала дешевые</option>
                    <option value="">Сначала дорогие</option>
                </select></div>
            <div class="testimonials__items">
                <div class="testimonials__item">
                    <div class="testimonials__avatar">
                        <div class="testimonials__avatar-letter">К</div>
                    </div>
                    <div class="testimonials__content">
                        <div class="testimonials__heading">
                            <h3 class="testimonials__name">Кристина М.</h3>
                            <div class="testimonials__info">Вчера, 14:07</div>
                            <div class="testimonials__info">Цвет товара: Ваниль</div>
                        </div>
                        <div class="testimonials__grade">
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div>
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                        </div>
                        <div class="testimonials__text">
                            <p>Замечательные часы, целый год на них смотрела. Заранее скачала приложение Galaxy Wearable, подключила часы сразу в пункте выдачи. Все работает!</p>
                        </div>
                    </div>
                </div>
                <div class="testimonials__item">
                    <div class="testimonials__avatar">
                        <div class="testimonials__avatar-letter">К</div>
                        <div class="testimonials__avatar-img"><img src="/images/testimonials/avatar1.jpg" /></div>
                    </div>
                    <div class="testimonials__content">
                        <div class="testimonials__heading">
                            <h3 class="testimonials__name">Анастасия А.</h3>
                            <div class="testimonials__info">16 апреля, 20:52</div>
                            <div class="testimonials__info">Цвет товара: Ваниль</div>
                        </div>
                        <div class="testimonials__grade">
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div>
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                        </div>
                        <div class="testimonials__text">
                            <p>Часы взяли девочке - диабетику шести лет, не громоздкие, очень удобные, ремешок пришлось поменять - родной велик, принимает смс и разговаривает по ним, с смс на уроке очень удобно.</p>
                        </div>
                        <div class="testimonials__answer">
                            <div class="testimonials__answer-heading">
                                <h4 class="testimonials__store">Samsung Russia</h4>
                                <div class="testimonials__info">16 апреля, 22:15</div>
                            </div>
                            <div class="testimonials__text">
                                <p>Наталия, здравствуйте! Спасибо за отзыв. Мы рады, что Вы оценили дизайн и удобство использования смарт-часов Samsung Galaxy Watch Active2. Для того, чтобы часы работали дольше от одного заряда аккумулятора, Вы можете оптимизировать их работу. Для этого зайдите на часах в меню Настройки -> Аккумулятор -> Оптимизация заряда -> проведите оптимизацию заряда. </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="testimonials__item">
                    <div class="testimonials__avatar">
                        <div class="testimonials__avatar-letter">С</div>
                    </div>
                    <div class="testimonials__content">
                        <div class="testimonials__heading">
                            <h3 class="testimonials__name">Сергей О.</h3>
                            <div class="testimonials__info">13 апреля, 20:41</div>
                            <div class="testimonials__info">Цвет товара: Ваниль</div>
                        </div>
                        <div class="testimonials__grade">
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div class="active">
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                            <div>
                              <svg
                              xmlns="http://www.w3.org/2000/svg"
                              xmlns:xlink="http://www.w3.org/1999/xlink"
                              width="17px" height="17px">
                              <path fill-rule="evenodd"  fill="currentColor"
                              d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                              </svg>
                            </div>
                        </div>
                        <div class="testimonials__text">
                            <p>Часы не реально крутые. Взяла за 14 к .К Самсунгу А 71 подключились за секунду. Благодаря в телефоне встроенному приложению Galaxy Wearable. Очень много функций в часах, на работе хожу в них как директор)))</p>
                            <div class="testimonials__photos">
                                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                                <div class="testimonials__photo"><a href="/images/testimonials/product1.jpg" data-fancybox="gallery"><img src="/images/testimonials/product1.jpg" /></a></div>
                            </div>
                        </div>
                    </div>
                </div><button class="btn btn--secondary">Показать еще отзывы</button>
            </div>
        </div>
        <div style="display: none;">
            <div class="testimonials-panel">
                <div class="testimonials-panel__grade">
                    <div class="testimonials-panel__grade-val">4.7</div>
                    <div class="testimonials-panel__grade-count"><span>2 649</span> отзывов</div>
                </div>
                <div class="testimonials-panel__item"><span>5</span>
                    <div class="testimonials-panel__graph">
                        <div class="testimonials-panel__graph-current" style="width: 71%"></div>
                    </div><span>71 %</span>
                </div>
                <div class="testimonials-panel__item"><span>4</span>
                    <div class="testimonials-panel__graph">
                        <div class="testimonials-panel__graph-current" style="width: 12%"></div>
                    </div><span>12 %</span>
                </div>
                <div class="testimonials-panel__item"><span>3</span>
                    <div class="testimonials-panel__graph">
                        <div class="testimonials-panel__graph-current" style="width: 5%"></div>
                    </div><span>5 %</span>
                </div>
                <div class="testimonials-panel__item"><span>2</span>
                    <div class="testimonials-panel__graph">
                        <div class="testimonials-panel__graph-current" style="width: 3%"></div>
                    </div><span>3 %</span>
                </div>
                <div class="testimonials-panel__item"><span>1</span>
                    <div class="testimonials-panel__graph">
                        <div class="testimonials-panel__graph-current" style="width: 9%"></div>
                    </div><span>9 %</span>
                </div><button class="btn btn--secondary">Оставить отзыв</button><a class="testimonials-panel__link" href="#">Правила оформления отзывов →</a>
            </div>
        </div>
    </div>
</section>
