<?php
$this->headTitle('Каталог товаров/'.$this->category, 'PREPEND');
//$this->headTitle(, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?><div class="container"  style="position:relative; max-width:1400px; min-height:calc(100vh - 160px) " >
    <div id="left-col">
        <div class="content-col">
            <?= $this->addressform ?>
            <!-- h2>Каталог </h2 -->
            <ul id="tree" class="tree" style="display:none">
                <?= $this->catalog ?>
            </ul>
            <div class=" testlegalstor" ></div>
        </div>               
    </div>
    <div id="main-col">
        <?= $this->bread ?> 
        
            <h2><?= $this->title ?> <?php if ($this->id) echo "<span>id: " . $this->id . "</span>"; ?></h2>
        <div id="tovar-list">
            <?= $this->product ?>
        </div>
    </div>               
</div>
</div>
