<?php

use Application\Resource\Resource;

//$this->headTitle(Resource::THE_CATALOG_OF_PRODUCTS, 'PREPEND');
$this->headTitle($this->category, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?><div class="container mainconteiner"  >
    <div  class="contentwrapper">
<?= $this->partial("/application/index/partials/product-page/bead-crumbs", ["breadCrumbs" => $this->breadCrumbs, "id" => $this->id]) ?>
        <h2><?= $this->title ?> <?php if (false and $this->id) echo "<span>id: " . $this->id . "</span>"; ?></h2>
        <div id="tovar-list">
            <div class="pw-contentblock cblock-2">         <div class="inactiveblok"></div></div>
            <div class="pw-contentblock gray iblokr cblock-2">Код товара: <?= $this->append['vendorCode'] ?></div>

            <div class="pw-contentblock cblock-3">
                <?= $this->partial("/application/index/partials/product-page/product-images", ["images" => $this->images, "image_path" => $this->imagePath('product')]) ?>
            </div>
            <div class="pw-contentblock cblock-3">
<?= $this->partial("/application/index/partials/product-page/main-characteristics", ["characteristics" => $this->characteristics]) ?>
            </div>

            <div class="pw-contentblock cblock-3">
                <?=
                $this->partial("/application/index/partials/product-page/pay-section",
                        [
                            "price" => $this->price,
                            "price_formated" => $this->price_formated,
                            "id" => $this->id,
                            "brand" => $this->brand,
                            "image_path" => $this->imagePath('brand'),
                ])
                ?>
            </div>
            <div class="blok">
                <div class="pw-contentblock cblock-5">
                    <?= $this->partial("/application/index/partials/product-page/description", ["description" => $this->description, "id" => $this->id]) ?>
<?= $this->partial("/application/index/partials/product-page/characteristics", ["characteristics" => $this->characteristics]) ?>
                </div>
                <div class="pw-contentblock cblock-3">
<?= $this->partial("/application/index/partials/product-page/append-info", ["params" => $this->append]) ?>
                </div>
            </div>
        </div>
    </div>
</div>
