<?php
$this->headTitle(Application\Resource\Resource::THE_CATALOG_OF_PRODUCTS."/".$this->category, 'PREPEND');
//$this->headTitle(, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?><div class="container mainconteiner"  >
    <div  class="contentwrapper">
            <h2><?= $this->title ?></h2>
        <div id="tovar-list">
            <?= $this->product ?>
        </div>
    </div>               
</div>

