<?php
//$this->headTitle(Application\Resource\Resource::THE_BRANDS, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/providers.js'));
?><section class="catalog">
  <div class="page-heading">
      <h1 class="h1"><?= $this->title ?>.  <?=$this->category_title ?> </h1>
        <span class="product-card__store-logo">
            <img src="/images/provider/<?=$this->logo?>"  />
        </span>
      <?= $this->partial("/application/common/catalog-sort", ['data' => $this->data])?>
  </div>
  <div class="catalog__wrap">

   <aside class="catalog__sidebar">
    <?= $this->partial("/application/index/partials/brand/bread-crumbs-menu", [ "url" => "seller", "breadCrumbs" => $this->breadCrumbs, "id" => $this->id, "category_id" => $this->category_id]) ?>
   </aside>

    <div class="catalog__content" id="provider-page">
      <section class="section">
        <div class="products-grid products-grid--3">
          <?= $this->partial("/application/common/product") ?>
        </div>
      </section>
    </div>
  </div>
</section>
