<?php
//$this->headTitle(Application\Resource\Resource::THE_BRANDS, 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
$this->inlineScript()->prependFile($this->basePath('/js/providers.js'));
?><section class="catalog">
  <div class="page-heading">
      <h1 class="h1"><?= $this->title ?>.  <?=$this->category_title ?> </h1>
        <span class="product-card__store-logo">
            <img src="/images/provider/<?=$this->logo?>"  />
        </span>
      <?= $this->partial("/application/common/catalog-sort", ['data' => $this->data])?>
  </div>
  <div class="catalog__wrap">

   <aside class="catalog__sidebar">
    <?= $this->partial("/application/index/partials/brand/bread-crumbs-menu", [ "url" => "seller", "breadCrumbs" => $this->breadCrumbs, "id" => $this->id, "category_id" => $this->category_id]) ?>
   </aside>

    <div class="catalog__content" id="provider-page">
      <section class="section">
        <div class="products-grid products-grid--3">
          <div v-for="(product, name) in products" :key="name" class="product">
              <div class="product__label" v-if="product.oldprice && product.oldprice != product.price">Акция</div>
              <a class="product__img" :href="'/product/' + name">
                <img :src="'<?= $this->imagePath('product').'/' ?>' + product.image" />
              </a>
              <a class="product__title" :href="'/product/' + name">{{ product.title }}</a>
              <div class="product__reviews">
                  <div class="product__reviews-grade">
                      <svg
                      xmlns="http://www.w3.org/2000/svg"
                      xmlns:xlink="http://www.w3.org/1999/xlink"
                      width="17px" height="17px">
                      <path fill-rule="evenodd"  fill="rgb(255, 75, 45)"
                      d="M3.788,16.998 C3.764,16.998 3.740,16.997 3.716,16.995 C3.230,16.947 2.869,16.488 2.916,15.973 L3.351,11.50 L0.224,7.340 C0.102,6.950 0.65,6.355 0.307,6.13 C0.419,5.910 0.557,5.837 0.703,5.803 L5.316,4.709 L7.739,0.457 C7.902,0.171 8.188,0.1 8.506,0.1 C8.664,0.1 8.820,0.46 8.958,0.131 C9.86,0.211 9.194,0.323 9.270,0.457 L11.693,4.720 L16.304,5.803 C16.784,5.917 17.86,6.421 16.977,6.926 C16.944,7.79 16.874,7.222 16.774,7.340 L13.658,11.40 L14.93,15.971 C14.136,16.485 13.773,16.942 13.283,16.987 C13.257,16.990 13.230,16.991 13.204,16.991 C13.84,16.991 12.967,16.966 12.856,16.917 L8.504,14.968 L4.152,16.917 C4.34,16.971 3.913,16.998 3.788,16.998 Z"/>
                      </svg>
                      <span>4.7</span>
                  </div>
                  <a class="product__reviews-link" href="#">28 отзывов</a>
              </div>
              <div class="product__price">
                  <div class="product__price-current">{{ (product.price / 100).toLocaleString() }} ₽</div>
                  <div v-if="product.oldprice && product.oldprice != product.price" class="product__price-old">{{ (product.oldprice / 100).toLocaleString() }} ₽</div>
              </div>
              <div class="product__tocart">
                <button class="btn btn--primary paybutton" :rel="name">В корзину</button>
              </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>
