<?php
$this->headTitle('User', 'PREPEND');
$this->headTitle($this->title, 'PREPEND');
?><div class="container"  style="position:relative; max-width:1600px; min-height:calc(100vh - 160px) " >
    <div id="left-col">
        <div class="content-col">
            <ul class='menu usermenu'>
                <?php //=$this->partial('application/index/partials/user-menu') 
                ?>
                <li><a href='#'>Профиль</a></li>
                <li><a href='#'>История заказов</a></li>
                <li><a href='#'>Мои адреса</a></li>
                <?=($this->auth)?"<li><a href='/clear-user-data' >Выход</a></li>":"";?>
                
            </ul>    

          

            <div class=" testlegalstor" ></div>
        </div>               
    </div>
    <div id="main-col">
        <!-- div class="bread-crumbs"><?= $this->bread ?></div--> 
        <div class="content-col" style="" id="tovary"> 


            <div id='ajaxfiltranswer'></div>
            <br class="both">
            <h1><?= $this->title ?>  <?=($this->id)?"<span>id: ". $this->id ."</span>":""?></h1>
            <div id="userdata"><?=(!$this->auth)?$this->partial('application/index/partials/auth-form'):$this->partial('application/index/partials/user-form') ?></div>
        </div>               
    </div>
</div>
